'use client'

import React from 'react'

export type NpcRole='science'|'engineering'|'operations'|'habitat'|'general'
export interface NpcVisualProfile{skin:string;hair:string;suit:string;accent:string;role:NpcRole;variant:number}
const SKIN=['#f0c7a1','#dba77d','#b97d58','#8b573d','#6d432f','#e2b88f']
const HAIR=['#2b211d','#51382b','#17191c','#756456','#b8aa91','#3d2c27']
const SUIT:Record<NpcRole,string>={science:'#d9e6e9',engineering:'#c78b39',operations:'#557f9a',habitat:'#78946a',general:'#9b8b72'}
const ACCENT:Record<NpcRole,string>={science:'#49c6e5',engineering:'#f0b84c',operations:'#72a9cf',habitat:'#8fc878',general:'#c7b88d'}
function h(s:string){let x=2166136261;for(let i=0;i<s.length;i++){x^=s.charCodeAt(i);x=Math.imul(x,16777619)}return x>>>0}
export function npcRole(role?:string|null):NpcRole{const r=(role??'').toLowerCase();if(/research|science|lab|fors|akadem|scient/.test(r))return'science';if(/engineer|tech|mine|drill|water|solar|wart|bau/.test(r))return'engineering';if(/log|trade|admin|oper|pilot|transport/.test(r))return'operations';if(/home|habitat|care|social|resident/.test(r))return'habitat';return'general'}
export function npcVisual(id:string,role?:string|null):NpcVisualProfile{const n=h(id),r=npcRole(role);return{skin:SKIN[n%SKIN.length],hair:HAIR[(n>>>4)%HAIR.length],suit:SUIT[r],accent:ACCENT[r],role:r,variant:(n>>>8)%4}}
export function NpcVisualStyles(){return <style>{`.npcv{position:relative;width:24px;height:38px;border:0;background:transparent;padding:0;cursor:pointer;filter:drop-shadow(0 3px 2px #0008)}.npcv .sh{position:absolute;left:2px;top:31px;width:20px;height:6px;border-radius:50%;background:#0008}.npcv .hair{position:absolute;left:7px;top:0;width:10px;height:6px;border-radius:6px 6px 2px 2px;background:var(--hair)}.npcv.v1 .hair{height:4px;border-radius:1px}.npcv.v2 .hair{left:5px;width:14px;height:8px}.npcv.v3 .hair:after{content:'';position:absolute;right:-3px;top:3px;width:4px;height:9px;background:var(--hair);border-radius:3px}.npcv .head{position:absolute;left:7px;top:4px;width:10px;height:10px;border-radius:45% 45% 48% 48%;background:var(--skin);border:1px solid #263442}.npcv .body{position:absolute;left:5px;top:14px;width:14px;height:14px;border-radius:3px 3px 2px 2px;background:var(--suit);border:1px solid #263442}.npcv .body:after{content:'';position:absolute;left:2px;right:2px;top:4px;height:2px;background:var(--accent)}.npcv .leg{position:absolute;top:27px;width:5px;height:9px;background:#263848}.npcv .l{left:5px}.npcv .r{left:14px}.npcv.walking .l{animation:npcwalk .5s infinite alternate}.npcv.walking .r{animation:npcwalk .5s infinite alternate-reverse}.npcv.selected{filter:drop-shadow(0 0 7px #ffe27b)}.npcv>span{position:absolute;top:-17px;left:50%;transform:translateX(-50%);white-space:nowrap;background:#07121eea;border:1px solid #52677a;color:#eee0c6;padding:2px 4px;font:7px monospace}.npcv>span small{display:block;color:var(--accent)}@keyframes npcwalk{from{transform:rotate(-15deg)}to{transform:rotate(15deg)}}`}</style>}
export function NpcFigure({id,name,role,moving=false,selected=false,showLabel=false,onClick}:{id:string;name:string;role?:string|null;moving?:boolean;selected?:boolean;showLabel?:boolean;onClick?:()=>void}){const v=npcVisual(id,role);return <button className={`npcv v${v.variant} ${moving?'walking':''} ${selected?'selected':''}`} style={{'--skin':v.skin,'--hair':v.hair,'--suit':v.suit,'--accent':v.accent} as React.CSSProperties} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onClick?.()}} title={`${name} · ${role??v.role}`}><i className="sh"/><i className="head"/><i className="hair"/><i className="body"/><i className="leg l"/><i className="leg r"/>{showLabel&&<span>{name.split(' ')[0]}<small>{role??v.role}</small></span>}</button>}
export function NpcPortrait({id,name,role}:{id:string;name:string;role?:string|null}){const v=npcVisual(id,role);return <div style={{display:'flex',gap:10,alignItems:'center',padding:'9px',border:'1px solid #344657',background:'#0b1622'}}><div style={{width:42,height:42,borderRadius:'50%',background:v.skin,border:`3px solid ${v.accent}`,position:'relative',overflow:'hidden'}}><i style={{position:'absolute,left:7,right:7,top:0,height:13,background:v.hair,borderRadius:'50% 50% 20% 20%'}}/><i style={{position:'absolute',left:8,right:8,bottom:0,height:12,background:v.suit}}/></div><div><b style={{color:'#f1d57a'}}>{name}</b><small style={{display:'block',color:v.accent,textTransform:'uppercase'}}>{role??v.role}</small></div></div>}
