import type { KnowledgeBuilding, KnowledgeLearningModule, KnowledgeUnlock } from './types';

export const learningModules: KnowledgeLearningModule[] = [
  {
    id: 'LRN:SSF:MAT-1001',
    name: 'Zahlen und Größen',
    domain: 'MAT',
    requires: [],
    teaches: ['CON:L1:zahlen', 'CON:L1:einheiten'],
    unlocks: ['UNL:SSF:basic-physics-ready'],
  },
  {
    id: 'LRN:SSF:MAT-1002',
    name: 'Vektoren und Richtung',
    domain: 'MAT',
    requires: ['LRN:SSF:MAT-1001'],
    teaches: ['CON:L1:vektoren'],
    unlocks: ['UNL:SSF:motion-ready'],
  },
  {
    id: 'LRN:SSF:PHY-1201',
    name: 'Bewegung und Geschwindigkeit',
    domain: 'PHY',
    requires: ['LRN:SSF:MAT-1002'],
    teaches: ['CON:L1:bewegung', 'CON:L1:geschwindigkeit'],
    unlocks: ['UNL:SSF:orbital-ready'],
  },
  {
    id: 'LRN:SSF:PHY-1101',
    name: 'Was ist Gravitation?',
    domain: 'PHY',
    requires: ['LRN:SSF:MAT-1001'],
    teaches: ['CON:L1:gravitation'],
    unlocks: ['UNL:NOX:orbital-navigation'],
  },
  {
    id: 'LRN:SSF:AST-2101',
    name: 'Orbitalmechanik Grundlagen',
    domain: 'AST',
    requires: ['LRN:SSF:PHY-1101', 'LRN:SSF:PHY-1201'],
    teaches: ['CON:L1:orbitalmechanik'],
    unlocks: ['UNL:NOX:transfer-routes'],
  },
  {
    id: 'LRN:SSF:PHY-1301',
    name: 'Was ist Energie?',
    domain: 'PHY',
    requires: ['LRN:SSF:MAT-1001'],
    teaches: ['CON:L1:energie'],
    unlocks: ['UNL:NOX:power-generation'],
  },
  {
    id: 'LRN:SSF:PHY-1302',
    name: 'Strom und Energiespeicher',
    domain: 'PHY',
    requires: ['LRN:SSF:PHY-1301'],
    teaches: ['CON:L1:elektrizitaet', 'CON:L1:energiespeicher'],
    unlocks: ['UNL:NOX:solar-grid'],
  },
  {
    id: 'LRN:SSF:CHE-1101',
    name: 'Wasser im Sonnensystem',
    domain: 'CHE',
    requires: ['LRN:SSF:PHY-1301'],
    teaches: ['CON:L1:wasser'],
    unlocks: ['UNL:NOX:water-processing'],
  },
  {
    id: 'LRN:SSF:AST-1201',
    name: 'Mars ist nicht die Erde',
    domain: 'AST',
    requires: ['LRN:SSF:CHE-1101'],
    teaches: ['CON:L1:atmosphaerenphysik', 'CON:L1:habitabilitaet'],
    unlocks: ['UNL:NOX:mars-habitat'],
  },
  {
    id: 'LRN:SSF:BIO-1101',
    name: 'Was ist Leben?',
    domain: 'BIO',
    requires: ['LRN:SSF:CHE-1101'],
    teaches: ['CON:L1:leben'],
    unlocks: ['UNL:NOX:controlled-biology'],
  },
  {
    id: 'LRN:SSF:BIO-1201',
    name: 'Photosynthese Grundlagen',
    domain: 'BIO',
    requires: ['LRN:SSF:BIO-1101'],
    teaches: ['CON:L1:photosynthese'],
    unlocks: ['UNL:NOX:greenhouse-systems'],
  },
  {
    id: 'LRN:SSF:MAT-1201',
    name: 'Stoffe und Materialien',
    domain: 'MAT',
    requires: ['LRN:SSF:MAT-1001'],
    teaches: ['CON:L1:materialien'],
    unlocks: ['UNL:NOX:resource-extraction'],
  },
  {
    id: 'LRN:SSF:CHE-1301',
    name: 'Metalle und Rohstoffe',
    domain: 'CHE',
    requires: ['LRN:SSF:MAT-1201'],
    teaches: ['CON:L1:metalle', 'CON:L1:rohstoffe'],
    unlocks: ['UNL:NOX:smelting'],
  },
  {
    id: 'LRN:SSF:TEC-1101',
    name: 'Werkzeuge und Maschinen',
    domain: 'TEC',
    requires: ['LRN:SSF:CHE-1301'],
    teaches: ['CON:L1:werkzeuge'],
    unlocks: ['UNL:NOX:industrial-tools'],
  },
  {
    id: 'LRN:SSF:TEC-1201',
    name: 'Fertigung Grundlagen',
    domain: 'TEC',
    requires: ['LRN:SSF:TEC-1101'],
    teaches: ['CON:L1:fertigung'],
    unlocks: ['UNL:NOX:industrial-production'],
  },
];

export const knowledgeUnlocks: KnowledgeUnlock[] = [
  { id: 'UNL:NOX:orbital-navigation', name: 'Orbitale Navigation', requires: ['LRN:SSF:PHY-1101'], unlocks: ['BLD:NOX:raumhafen-1'] },
  { id: 'UNL:NOX:transfer-routes', name: 'Transferrouten', requires: ['LRN:SSF:AST-2101'], unlocks: ['BLD:NOX:frachtkontrolle-1'] },
  { id: 'UNL:NOX:power-generation', name: 'Energieerzeugung', requires: ['LRN:SSF:PHY-1301'], unlocks: ['BLD:NOX:solarfeld-1'] },
  { id: 'UNL:NOX:solar-grid', name: 'Solarnetz', requires: ['LRN:SSF:PHY-1302'], unlocks: ['BLD:NOX:batteriespeicher-1'] },
  { id: 'UNL:NOX:water-processing', name: 'Wasseraufbereitung', requires: ['LRN:SSF:CHE-1101'], unlocks: ['BLD:NOX:wasseraufbereitung-1'] },
  { id: 'UNL:NOX:mars-habitat', name: 'Mars Habitat', requires: ['LRN:SSF:AST-1201'], unlocks: ['BLD:NOX:mars-habitat-1'] },
  { id: 'UNL:NOX:controlled-biology', name: 'Kontrollierte Biologie', requires: ['LRN:SSF:BIO-1101'], unlocks: ['BLD:NOX:biolabor-1'] },
  { id: 'UNL:NOX:greenhouse-systems', name: 'Gewächshaussysteme', requires: ['LRN:SSF:BIO-1201'], unlocks: ['BLD:NOX:gewaechshaus-1', 'BLD:NOX:nahrungsproduktion-1'] },
  { id: 'UNL:NOX:resource-extraction', name: 'Rohstoffgewinnung', requires: ['LRN:SSF:MAT-1201'], unlocks: ['BLD:NOX:mine-1'] },
  { id: 'UNL:NOX:smelting', name: 'Schmelztechnik', requires: ['LRN:SSF:CHE-1301'], unlocks: ['BLD:NOX:schmelze-1'] },
];

export const knowledgeBuildings: KnowledgeBuilding[] = [
  { id: 'BLD:NOX:raumhafen-1', name: 'Raumhafen I', category: 'transport', requires: ['UNL:NOX:orbital-navigation'], effects: ['local_trade', 'ship_operations'] },
  { id: 'BLD:NOX:frachtkontrolle-1', name: 'Frachtkontrolle I', category: 'logistics', requires: ['UNL:NOX:transfer-routes'], effects: ['route_planning', 'cargo_management'] },
  { id: 'BLD:NOX:solarfeld-1', name: 'Solarfeld I', category: 'energy', requires: ['UNL:NOX:power-generation'], effects: ['energy_production'] },
  { id: 'BLD:NOX:batteriespeicher-1', name: 'Batteriespeicher I', category: 'energy', requires: ['UNL:NOX:solar-grid'], effects: ['energy_storage'] },
  { id: 'BLD:NOX:wasseraufbereitung-1', name: 'Wasseraufbereitung I', category: 'life_support', requires: ['UNL:NOX:water-processing'], effects: ['water_supply'] },
  { id: 'BLD:NOX:mars-habitat-1', name: 'Mars Habitat I', category: 'colony', requires: ['UNL:NOX:mars-habitat'], effects: ['population_capacity', 'life_support'] },
  { id: 'BLD:NOX:biolabor-1', name: 'Biolabor I', category: 'science', requires: ['UNL:NOX:controlled-biology'], effects: ['biological_research'] },
  { id: 'BLD:NOX:gewaechshaus-1', name: 'Gewächshaus I', category: 'food', requires: ['UNL:NOX:greenhouse-systems'], effects: ['food_production'] },
  { id: 'BLD:NOX:nahrungsproduktion-1', name: 'Nahrungsproduktion I', category: 'food', requires: ['UNL:NOX:greenhouse-systems'], effects: ['colony_food_supply'] },
  { id: 'BLD:NOX:mine-1', name: 'Mine I', category: 'extraction', requires: ['UNL:NOX:resource-extraction'], effects: ['ore_production'] },
  { id: 'BLD:NOX:schmelze-1', name: 'Schmelze I', category: 'industry', requires: ['UNL:NOX:smelting'], effects: ['metal_production'] },
];
