'use client'

import { useEffect, useState } from 'react'

type Area={label:'A'|'B'|'C';usableAreaHa:number;usableShare:number;maxConnectedSpanM:number;expansionScore:number;corridorScore:number;accessScore:number;areaScore:number;verdict:'strong'|'conditional'|'weak';notes:string[]}
type Corridor={label:'A'|'B'|'C';straightLineDistanceM:number;sourceResolutionM:number;sampledCells:number;elevationDeltaM:number|null;surfaceReliefM:number|null;maxObservedSurfaceSlopePercent:number|null}
type CatapultCandidate={id:string;rank:number;score:number;azimuthDeg:number;analysedLengthM:number;elevationGainM:number;averageGradePercent:number;maxSegmentGradePercent:number;monotonicClimbShare:number;sundernHubDistanceM:number;selmeckeDistanceM:number;departureConflictDistanceM:number|null;departureConflictType:string|null;sourceResolutionM:number}
type CatapultScreening={status:'planning-only-not-canonical';hub:{precision:'regional-anchor-only'};parameters:{targetLengthM:number;desiredAverageGradePercent:[number,number];testedAzimuthStepDeg:number};candidates:CatapultCandidate[]}
type Payload={ok:boolean;areaAnalysis?:Area[];corridorAnalysis?:Corridor[];catapultCorridorScreening?:CatapultScreening;recommendedArea?:Area|null;error?:string}

const km=(value:number)=>`${(value/1000).toFixed(1)} km`

export default function SpaceportAreaComparison(){
 const[data,setData]=useState<Payload|null>(null)
 useEffect(()=>{fetch('/api/earth/spaceport-candidates?radiusKm=6').then(r=>r.json()).then(setData).catch(e=>setData({ok:false,error:String(e)}))},[])
 if(!data)return <section className="area-compare">Flächenprüfung wird geladen …</section>
 if(!data.ok||!data.areaAnalysis)return <section className="area-compare">Flächenprüfung derzeit nicht verfügbar: {data.error}</section>
 const recommended=data.recommendedArea?.label,catapult=data.catapultCorridorScreening
 return <section className="area-compare">
  <div className="area-head"><div><small>FLÄCHENPRÜFUNG · SAUERLAND</small><h2>A–C im direkten Vergleich</h2></div><p>Die bisherigen Flächen bleiben Vergleichsdaten. Kein Standort wird dadurch kanonisiert oder bebaut.</p></div>
  <div className="cards">{data.areaAnalysis.map(area=>{const corridor=data.corridorAnalysis?.find(item=>item.label===area.label);return <article key={area.label} className={recommended===area.label?'best':''}>
   <div className="card-top"><b>{area.label}</b><strong>{area.areaScore}/100</strong></div><span className={`verdict ${area.verdict}`}>{area.verdict==='strong'?'stark':area.verdict==='conditional'?'bedingt geeignet':'schwach'}</span>{recommended===area.label&&<em>stärkste Bestandsfläche</em>}
   <dl><div><dt>nutzbare Fläche</dt><dd>{area.usableAreaHa.toFixed(1)} ha</dd></div><div><dt>nutzbarer Anteil</dt><dd>{Math.round(area.usableShare*100)} %</dd></div><div><dt>Korridor</dt><dd>{area.maxConnectedSpanM} m</dd></div><div><dt>Erweiterung</dt><dd>{area.expansionScore}/100</dd></div><div><dt>Erschließung</dt><dd>{area.accessScore}/100</dd></div><div><dt>Korridor-Score</dt><dd>{area.corridorScore}/100</dd></div></dl>
   {corridor&&<div className="route-screen"><b>Selmecke-Verbindung · alte Vorprüfung</b><dl><div><dt>Luftlinie</dt><dd>{km(corridor.straightLineDistanceM)}</dd></div><div><dt>Höhendifferenz</dt><dd>{corridor.elevationDeltaM==null?'offen':`${corridor.elevationDeltaM>0?'+':''}${corridor.elevationDeltaM.toFixed(0)} m`}</dd></div><div><dt>Oberflächenrelief</dt><dd>{corridor.surfaceReliefM==null?'offen':`${corridor.surfaceReliefM.toFixed(0)} m`}</dd></div><div><dt>max. Neigung</dt><dd>{corridor.maxObservedSurfaceSlopePercent==null?'offen':`${corridor.maxObservedSurfaceSlopePercent.toFixed(1)} %`}</dd></div></dl><small>≈ {corridor.sourceResolutionM} m Quelldatensatz · {corridor.sampledCells} Proben · keine Tunnelplanung</small></div>}
   <p>{area.notes.join(' · ')}</p>
  </article>})}</div>
  <div className="catapult-head"><div><small>GERICHTETE HANGSUCHE · NEUER PLANUNGSSTAND</small><h2>Katapultkorridore außerhalb Sunderns</h2></div><p>Sundern dient nur als regionaler Verkehrs- und Betriebsanker. Die Richtung beschreibt die Geländeachse, nicht einen freigegebenen Orbitalazimut.</p></div>
  {!catapult?.candidates.length?<div className="catapult-empty">Im aktuellen groben Raster wurde noch kein ausreichend langer, durchgehend ansteigender Hangkorridor aufgelöst. Für die nächste Stufe ist ein größeres und feineres DEM erforderlich.</div>:<div className="catapult-cards">{catapult.candidates.slice(0,3).map(item=><article key={item.id}>
   <div className="card-top"><b>H{item.rank}</b><strong>{item.score}/100</strong></div><span className="verdict conditional">nur Vorprüfung</span>
   <dl><div><dt>Hangachse</dt><dd>{item.azimuthDeg.toFixed(1)}°</dd></div><div><dt>untersuchte Länge</dt><dd>{km(item.analysedLengthM)}</dd></div><div><dt>Höhengewinn</dt><dd>+{item.elevationGainM.toFixed(0)} m</dd></div><div><dt>mittlere Steigung</dt><dd>{item.averageGradePercent.toFixed(1)} %</dd></div><div><dt>max. Segment</dt><dd>{item.maxSegmentGradePercent.toFixed(1)} %</dd></div><div><dt>ansteigender Anteil</dt><dd>{Math.round(item.monotonicClimbShare*100)} %</dd></div><div><dt>Distanz Sundern</dt><dd>{km(item.sundernHubDistanceM)}</dd></div><div><dt>Distanz Selmecke</dt><dd>{km(item.selmeckeDistanceM)}</dd></div></dl>
   <p className="departure">Ausflugzone: {item.departureConflictDistanceM==null?'kein Konflikt im groben OSM-Korridor gefunden':`${item.departureConflictType} nach etwa ${item.departureConflictDistanceM} m`}.</p><small>≈ {item.sourceResolutionM} m Suchraster · Orbitalrichtung, Abbruchräume, Lärm, Geologie und Genehmigung offen</small>
  </article>)}</div>}
  <style jsx>{`.area-compare{background:#eef0e8;color:#1f3440;padding:8px 22px 34px;font-family:system-ui,sans-serif}.area-head,.catapult-head{max-width:1500px;margin:0 auto 12px;display:flex;justify-content:space-between;gap:30px;align-items:end}.catapult-head{margin-top:24px;padding-top:20px;border-top:1px solid #c6c9bf}.area-head small,.catapult-head small{letter-spacing:.14em;font-weight:800;color:#657b87}.area-head h2,.catapult-head h2{font-family:Georgia,serif;font-weight:400;margin:4px 0 0}.area-head p,.catapult-head p{max-width:680px;margin:0;font-size:11px;color:#6f7c7d}.cards,.catapult-cards{max-width:1500px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.cards article,.catapult-cards article{position:relative;background:#faf9f3;border:1px solid #c6c9bf;border-radius:10px;padding:14px}.cards article.best{border-color:#a8893d;box-shadow:0 5px 20px #8d762226}.catapult-cards article{border-style:dashed;border-color:#9b7d35;background:#fffaf0}.card-top{display:flex;justify-content:space-between;align-items:center}.card-top b{font-family:Georgia,serif;font-size:28px}.card-top strong{font-size:20px;color:#9a7622}.verdict{display:inline-block;margin:5px 0 8px;border-radius:99px;padding:3px 7px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.verdict.strong{background:#dcebd5;color:#3d6534}.verdict.conditional{background:#f1e7c6;color:#755c18}.verdict.weak{background:#eedbd5;color:#7d4336}article em{position:absolute;right:14px;top:45px;font-size:9px;color:#8d6d1d;font-style:normal;font-weight:800}dl{margin:4px 0 8px;display:grid;grid-template-columns:1fr 1fr;gap:5px 14px}dl div{display:flex;justify-content:space-between;border-bottom:1px solid #e1e2db;padding:4px 0}dt{font-size:10px;color:#748080}dd{font-size:10px;font-weight:800;margin:0}.route-screen{margin:10px 0;padding:9px;border-radius:7px;background:#eef2ec;border:1px solid #d2d8cf}.route-screen>b{font-size:10px;color:#46606a}.route-screen dl{margin-top:5px}.route-screen small,.catapult-cards small{display:block;color:#718080;font-size:9px;line-height:1.35}article p{margin:5px 0 0;font-size:10px;line-height:1.45;color:#536267}.departure{padding:7px;background:#f2ead2;border-radius:6px;margin:9px 0!important}.catapult-empty{max-width:1500px;margin:auto;padding:14px;border:1px dashed #9b7d35;border-radius:9px;background:#fffaf0;color:#65572f;font-size:11px}@media(max-width:850px){.area-head,.catapult-head{display:block}.area-head p,.catapult-head p{margin-top:6px}.cards,.catapult-cards{grid-template-columns:1fr}}`}</style>
 </section>
}
