/**
 * Canonical character intake for literary crossovers.
 * Metadata only. No people rows, NPC actions, religion scores, or knowledge are
 * generated by registering a character. Existing CanonicalCharacterRef binds
 * an actual person to an external source only after a separate canonical review.
 */
export interface LiteraryCharacterIntake {
  characterKey: string
  displayName: string
  sourceWork: string
  intendedRole: string
  sourceReference: string
  state: 'source_review' | 'ready_for_binding'
  limitations: readonly string[]
}

export const LITERARY_CHARACTER_INTAKE: readonly LiteraryCharacterIntake[] = [
  {
    characterKey: 'aristeas-lux',
    displayName: 'Aristeas Lux',
    sourceWork: 'Aristeas Lux / DaVaRu',
    intendedRole: 'Interpret und Erzähler der DaVaRu-Tradition',
    sourceReference: 'Google Drive: Charakter Aristeas Lux.docx',
    state: 'source_review',
    limitations: [
      'Deutungen sind persönliche Interpretationen, keine privilegierte Weltwahrheit',
      'Keine fest implementierten übernatürlichen Fähigkeiten',
      'Klang/Frequenz nicht als allumfassendes Erklärungsprinzip unterstellen',
    ],
  },
  {
    characterKey: 'xerxes-gefaelle',
    displayName: 'Xerxes',
    sourceWork: 'Das Gefälle / Xerxes',
    intendedRole: 'Buchfigur als eigenständiger Einwohner in der NOXIA-Welt',
    sourceReference: 'Google Drive: OTA-LIT-0004-2026.docx',
    state: 'source_review',
    limitations: [
      'Mishkenaz versteht er, spricht es aber zunächst nicht vollständig',
      'Ursprüngliche Zeitstellung Jahr 68–72 V.Ä. nicht ungeprüft auf NOXIA-Zeitachse übertragen',
      'Literarischer Kanon und neue Simulationserfahrungen trennen',
    ],
  },
  {
    characterKey: 'mr-marx-endia',
    displayName: 'Mr. Marx',
    sourceWork: 'ENDIA',
    intendedRole: 'CEO mit eigener Unternehmensrolle im NOXIA-Universum',
    sourceReference: 'Google Drive: Liv Dawn - der Plan funktioniert - noch.docx',
    state: 'source_review',
    limitations: [
      'Vorlage nennt die YoSunVR-Zentrale als Schauplatz seines Büros',
      'Unternehmensidentität und wirtschaftliche Rechte erst gegen NOXIA-Kanon prüfen',
      'CEO-Titel allein erzeugt keine Eigentums-, Geld- oder Verwaltungsrechte',
    ],
  },
]

export function getLiteraryCharacterIntake(key: string): LiteraryCharacterIntake | undefined {
  return LITERARY_CHARACTER_INTAKE.find(entry => entry.characterKey === key)
}
