'use client'

import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{LOCATION_MAPS,terrainCodeToType}from'@/lib/grid/locationMaps'
import{isBuildable}from'@/lib/grid/generateGrid'
import{getToken}from'@/lib/supabase/auth'

const ROOT='/assets/environments/earth/sauerland',TW=86,TH=43,SW=2800,SH=1650,OX=1390,OY=120
type Cardinal='N'|'E'|'S'|'W';type Direction=Cardinal|'NE'|'SE'|'SW'|'NW';type Point={row:number;col:number}
type Entity={id:string;entity_id:string;entity_type:string;tile_row:number;tile_col:number;locations?:{slug?:string|null;name?:string|null}|null}
type BuildOption={key:string;name:string;displayCost:number;knowledgeLocked:boolean;siteBlocked:boolean;learningUrl?:string|null}
const EARTH=LOCATION_MAPS.earth,ROWS=EARTH.length,COLS=EARTH[0]?.length??32,CARDINAL:Cardinal[]=['N','E','S','W'],DIR8:Direction[]=['N','NE','E','SE','S','SW','W','NW']
const DELTA:Record<Cardinal,[number,number]>={N:[-1,0],E:[0,1],S:[1,0],W:[0,-1]}
const btn:React.CSSProperties={height:32,minWidth:34,border:'1px solid #d8d0c2',borderRadius:7,background:'#fff',color:'#24415e',fontWeight:700,cursor:'pointer',padding:'0 10px'}
const iso=(r:number,c:number)=>({x:OX+(c-r)*TW/2,y:OY+(c+r)*TH/2}),key=(r:number,c:number)=>`${r}:${c}`
const neighbours=(set:Set<string>,r:number,c:number)=>CARDINAL.filter(d=>{const[dr,dc]=DELTA[d];return set.has(key(r+dr,c+dc))})
const buildable=(r:number,c:number)=>isBuildable(terrainCodeToType(EARTH[r]?.[c]??'g'))

function Sprite({src,frames,frame,size=104,title}:{src:string;frames:number;frame:number;size?:number;title?:string}){const f=Math.max(0,Math.min(frames-1,frame));return <div title={title} style={{width:size,height:size,background:`url(${src}) ${frames===1?0:(f/(frames-1))*100}% 0/${frames*100}% 100% no-repeat`,filter:'drop-shadow(0 6px 4px #26351f44)',pointerEvents:title?'auto':'none'}}/>}
// Orientation sheets are authored as top-down square cells. GroundSprite projects
// the selected cell into the same 2:1 diamond plane as the world. This removes
// the upright green "walls" produced by rendering the sheets as ordinary sprites.
function GroundSprite({src,frames,frame}:{src:string;frames:number;frame:number}){const f=Math.max(0,Math.min(frames-1,frame));return <div style={{width:TW,height:TW,background:`url(${src}) ${frames===1?0:(f/(frames-1))*100}% 0/${frames*100}% 100% no-repeat`,transform:'rotate(45deg) scaleY(.5)',transformOrigin:'50% 50%',pointerEvents:'none'}}/>}

function connectedGraphic(kind:'road'|'river',dirs:Cardinal[]){const has=(d:Cardinal)=>dirs.includes(d),base=kind==='road'?`${ROOT}/transport`:`${ROOT}/water`
 if(dirs.length>=4)return kind==='road'?{src:`${base}/road_cross_01.svg`,frames:1,frame:0}:{src:`${base}/water_river_y_01/orientations_8.svg`,frames:8,frame:0}
 if(dirs.length===3){const miss=CARDINAL.find(d=>!has(d))??'N';return{src:kind==='road'?`${base}/road_t_01/orientations_4.svg`:`${base}/water_river_t_01/orientations_4.svg`,frames:4,frame:CARDINAL.indexOf(miss)}}
 if(dirs.length===2){const straight=(has('N')&&has('S'))||(has('E')&&has('W'));if(straight)return{src:kind==='road'?`${base}/road_straight_01/orientations_4.svg`:`${base}/water_river_straight_01/orientations_4.svg`,frames:4,frame:has('N')?0:1};const pair=dirs.slice().sort().join(''),curve:Record<string,number>={EN:0,ES:2,SW:4,NW:6};return{src:kind==='road'?`${base}/road_curve_01/orientations_8.svg`:`${base}/water_river_curve_01/orientations_8.svg`,frames:8,frame:curve[pair]??0}}
 const d=dirs[0]??'N';return{src:kind==='road'?`${base}/road_straight_01/orientations_4.svg`:`${base}/water_river_straight_01/orientations_4.svg`,frames:4,frame:d==='E'||d==='W'?1:0}}

function buildingAsset(id:string){const v=id.toLowerCase();if(v.includes('school')||v.includes('academy'))return['buildings/school_01',0]as const;if(v.includes('admin')||v.includes('town'))return['buildings/town_hall_01',1]as const;if(v.includes('factory')||v.includes('smelt')||v.includes('industrial'))return['buildings/factory_small_01',2]as const;if(v.includes('warehouse')||v.includes('storage')||v.includes('depot'))return['buildings/warehouse_01',1]as const;if(v.includes('farm')||v.includes('plant'))return['buildings/farm_01',2]as const;if(v.includes('hangar'))return['hub/hub_hangar_01',3]as const;if(v.includes('tower'))return['hub/hub_tower_01',3]as const;if(v.includes('spaceport')||v.includes('landing'))return[v.includes('mini')?'hub/hub_pad_mini_01':v.includes('service')?'hub/hub_service_01':v.includes('storage')?'hub/hub_storage_01':v.includes('pad')?'hub/hub_pad_standard_01':'hub/hub_control_01',0]as const;if(v.includes('habitat')||v.includes('house')||v.includes('residential'))return['buildings/house_01',2]as const;return['hub/hub_module_01',0]as const}
function terrain(code:string,r:number,c:number){const t=terrainCodeToType(code);if(t==='tile_farmland')return`#b98f54 url(${ROOT}/terrain/terrain_field_01.svg) center/cover`;if(t==='tile_city'||t==='tile_concrete')return`#8d927e url(${ROOT}/terrain/terrain_rocky_01.svg) center/cover`;if(t==='tile_forest_dense')return`#587a45 url(${ROOT}/terrain/terrain_grass_dark_01.svg) center/cover`;if(t==='tile_forest_edge')return`#70915a url(${ROOT}/terrain/terrain_grass_dark_01.svg) center/cover`;if(t==='river')return`#668b43 url(${ROOT}/terrain/terrain_grass_01.webp) center/cover`;const a=(r*17+c*29)%17===0?'terrain_grass_dark_01.svg':'terrain_grass_01.webp';return`#86a76d url(${ROOT}/terrain/${a}) center/cover`}

export default function Page(){const view=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;l:number;t:number;m:boolean}|null>(null);const[zoom,setZoom]=useState(.72),[entities,setEntities]=useState<Entity[]>([]),[status,setStatus]=useState('Weltdaten werden geladen …'),[buildMode,setBuildMode]=useState(false),[selected,setSelected]=useState<Point|null>(null),[options,setOptions]=useState<BuildOption[]>([]),[building,setBuilding]=useState(false),[message,setMessage]=useState('')
 const load=useCallback(async()=>{try{const res=await fetch('/api/game/world');if(!res.ok)throw new Error();const w=await res.json(),all=Array.isArray(w.entities)?w.entities as Entity[]:[],earth=all.filter(e=>{const s=e.locations?.slug?.toLowerCase()??'',n=e.locations?.name?.toLowerCase()??'';return s==='earth'||s==='erde'||s.includes('sauerland')||n.includes('erde')||n.includes('sauerland')});setEntities(earth);setStatus(`${earth.filter(e=>e.entity_type==='building').length} Gebäude · Sauerland 2086`)}catch{setStatus('Weltdaten nicht erreichbar')}},[]);useEffect(()=>{void load()},[load])
 const roads=useMemo(()=>entities.filter(e=>(e.entity_type==='road'||e.entity_id==='road')&&Number.isFinite(e.tile_row)&&Number.isFinite(e.tile_col)).map(e=>({row:e.tile_row,col:e.tile_col})),[entities]),roadSet=useMemo(()=>new Set(roads.map(p=>key(p.row,p.col))),[roads])
 const river=useMemo(()=>{const a:Point[]=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(EARTH[r]?.[c]==='r')a.push({row:r,col:c});return a},[]),riverSet=useMemo(()=>new Set(river.map(p=>key(p.row,p.col))),[river])
 const buildings=useMemo(()=>entities.filter(e=>e.entity_type==='building'&&Number.isFinite(e.tile_row)&&Number.isFinite(e.tile_col)),[entities]),occupied=useMemo(()=>new Set(buildings.map(e=>key(e.tile_row,e.tile_col))),[buildings])
 const setZ=useCallback((n:number)=>{const v=view.current,z=Math.max(.34,Math.min(2.1,n));if(!v){setZoom(z);return}const old=zoom,cx=v.scrollLeft+v.clientWidth/2,cy=v.scrollTop+v.clientHeight/2;setZoom(z);requestAnimationFrame(()=>{v.scrollLeft=cx*z/old-v.clientWidth/2;v.scrollTop=cy*z/old-v.clientHeight/2})},[zoom]);useEffect(()=>{const v=view.current;if(!v)return;const wh=(e:WheelEvent)=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();setZ(zoom*(e.deltaY<0?1.12:.89))};v.addEventListener('wheel',wh,{passive:false});return()=>v.removeEventListener('wheel',wh)},[zoom,setZ]);useEffect(()=>{const v=view.current;if(v)requestAnimationFrame(()=>{v.scrollLeft=Math.max(0,SW*zoom/2-v.clientWidth/2);v.scrollTop=20})},[])
 const choose=useCallback(async(r:number,c:number)=>{if(!buildMode||occupied.has(key(r,c))||!buildable(r,c))return;setSelected({row:r,col:c});setOptions([]);setMessage('Lade Baumöglichkeiten …');try{const token=await getToken(),type=terrainCodeToType(EARTH[r]?.[c]??'g'),res=await fetch(`/api/game/build/options?location=earth&tileType=${encodeURIComponent(type)}&tileRow=${r}&tileCol=${c}`,{headers:token?{Authorization:`Bearer ${token}`}:{}}),d=await res.json();setOptions(Array.isArray(d.buildable)?d.buildable:[]);setMessage('')}catch{setMessage('Baumöglichkeiten konnten nicht geladen werden.')}},[buildMode,occupied])
 const start=useCallback(async(o:BuildOption)=>{if(!selected||o.knowledgeLocked||o.siteBlocked||building)return;setBuilding(true);try{const token=await getToken(),p=new URLSearchParams({action:'start',buildableId:o.key,location:'earth',tileRow:String(selected.row),tileCol:String(selected.col),tileLevel:'0'}),res=await fetch(`/api/game/build?${p}`,{headers:token?{Authorization:`Bearer ${token}`}:{}}),d=await res.json();if(!res.ok)throw new Error(d.error||'Bau fehlgeschlagen');setMessage(`${o.name.replace(/^🔒 /,'')} wurde beauftragt.`);setSelected(null);setOptions([]);await load()}catch(e){setMessage(e instanceof Error?e.message:'Bau fehlgeschlagen')}finally{setBuilding(false)}},[selected,building,load])
 const forest=[]as Array<{row:number;col:number;asset:string}>;for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const code=EARTH[r]?.[c];if(code!=='f'&&code!=='F')continue;if(code==='f'&&(r*13+c*7)%3===0)continue;const a=code==='F'?['tree_conifer_01.svg','tree_conifer_02.svg','tree_broadleaf_01.svg']:['tree_birch_01.svg','tree_broadleaf_02.svg','tree_conifer_01.svg'];forest.push({row:r,col:c,asset:a[(r*5+c*11)%a.length]})}
 const moving=[{row:19,col:24,a:'car_01',d:'E'as Direction,s:58},{row:19,col:29,a:'service_01',d:'W'as Direction,s:62},{row:17,col:27,a:'drone_01',d:'SE'as Direction,s:58}]
 return <main style={{position:'fixed',inset:0,zIndex:10000,background:'#e9eee3',fontFamily:'system-ui',display:'grid',gridTemplateRows:'58px 1fr'}}><header style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 16px',background:'#fbfaf6',borderBottom:'1px solid #d7d0c4',zIndex:20}}><div><strong style={{color:'#23415d'}}>THARSIS HUB · SAUERLAND</strong><span style={{marginLeft:12,color:'#7d7467',fontSize:11}}>{status}</span></div><div style={{display:'flex',gap:6,alignItems:'center'}}><button onClick={()=>setBuildMode(v=>!v)} style={{...btn,background:buildMode?'#23415d':'#fff',color:buildMode?'#fff':'#24415e'}}>🏗 Bauen</button><button onClick={()=>setZ(zoom-.12)} style={btn}>−</button><small>{Math.round(zoom*100)}%</small><button onClick={()=>setZ(zoom+.12)} style={btn}>+</button><button onClick={()=>setZ(1)} style={btn}>100%</button><button onClick={()=>history.back()} style={btn}>← Zurück</button></div></header><div ref={view} onMouseDown={e=>{const v=view.current;if(v){drag.current={x:e.clientX,y:e.clientY,l:v.scrollLeft,t:v.scrollTop,m:false};v.style.cursor='grabbing'}}} onMouseMove={e=>{const v=view.current,d=drag.current;if(v&&d){const x=e.clientX-d.x,y=e.clientY-d.y;if(Math.abs(x)+Math.abs(y)>4)d.m=true;v.scrollLeft=d.l-x;v.scrollTop=d.t-y}}} onMouseUp={()=>{drag.current=null;if(view.current)view.current.style.cursor=buildMode?'crosshair':'grab'}} style={{overflow:'auto',cursor:buildMode?'crosshair':'grab',background:'linear-gradient(#cfe0e7 0 10%,#dfe8cf 28%,#cad8b1)',overscrollBehavior:'contain'}}><div style={{position:'relative',width:SW*zoom,height:SH*zoom}}><div style={{position:'absolute',width:SW,height:SH,transform:`scale(${zoom})`,transformOrigin:'top left'}}>
 {Array.from({length:ROWS}).flatMap((_,r)=>Array.from({length:COLS}).map((__,c)=>{const p=iso(r,c);return <div key={`t${r}-${c}`} style={{position:'absolute',left:p.x-TW/2,top:p.y-TH/2,width:TW+.7,height:TH+.7,clipPath:'polygon(50% 0,100% 50%,50% 100%,0 50%)',background:terrain(EARTH[r]?.[c]??'g',r,c),zIndex:r+c}}/>}))}
 {river.map((q,i)=>{const p=iso(q.row,q.col),g=connectedGraphic('river',neighbours(riverSet,q.row,q.col));return <div key={`w${i}`} style={{position:'absolute',left:p.x-TW/2,top:p.y-TW/2,zIndex:80+q.row+q.col}}><GroundSprite {...g}/></div>})}
 {roads.map((q,i)=>{const p=iso(q.row,q.col),g=connectedGraphic('road',neighbours(roadSet,q.row,q.col));return <div key={`r${i}`} style={{position:'absolute',left:p.x-TW/2,top:p.y-TW/2,zIndex:100+q.row+q.col}}><GroundSprite {...g}/></div>})}
 {forest.map((o,i)=>{const p=iso(o.row,o.col);return <img key={`f${i}`} src={`${ROOT}/nature/${o.asset}`} alt="" style={{position:'absolute',left:p.x-28,top:p.y-54,width:56,height:62,objectFit:'contain',zIndex:140+o.row+o.col,pointerEvents:'none'}}/>})}
 {buildings.slice().sort((a,b)=>a.tile_row+a.tile_col-b.tile_row-b.tile_col).map(e=>{const p=iso(e.tile_row,e.tile_col),[path,frame]=buildingAsset(e.entity_id);return <div key={e.id} style={{position:'absolute',left:p.x-55,top:p.y-92,zIndex:300+e.tile_row+e.tile_col}}><Sprite src={`${ROOT}/${path}/turnaround_4.svg`} frames={4} frame={frame} size={110} title={e.entity_id.replace(/_/g,' ')}/></div>})}
 {moving.map((o,i)=>{const p=iso(o.row,o.col);return <div key={`m${i}`} style={{position:'absolute',left:p.x-o.s/2,top:p.y-o.s*.72,zIndex:420+o.row+o.col}}><Sprite src={`${ROOT}/vehicles/${o.a}/turnaround_8.svg`} frames={8} frame={DIR8.indexOf(o.d)} size={o.s}/></div>})}
 {buildMode&&Array.from({length:ROWS}).flatMap((_,r)=>Array.from({length:COLS}).map((__,c)=>{const p=iso(r,c),blocked=occupied.has(key(r,c))||!buildable(r,c),active=selected?.row===r&&selected?.col===c;return <button key={`h${r}-${c}`} disabled={blocked} onClick={e=>{e.stopPropagation();if(!drag.current?.m)void choose(r,c)}} style={{position:'absolute',left:p.x-TW/2,top:p.y-TH/2,width:TW,height:TH,clipPath:'polygon(50% 0,100% 50%,50% 100%,0 50%)',background:active?'#ecbf4c66':'#fff0',border:0,cursor:blocked?'not-allowed':'crosshair',zIndex:700+r+c}}/>}))}</div></div></div>
 {buildMode&&<aside style={{position:'fixed',right:18,top:76,width:330,maxHeight:'calc(100vh - 96px)',overflow:'auto',zIndex:12000,background:'#fbfaf6f8',border:'1px solid #d7d0c4',borderRadius:12,padding:14,boxShadow:'0 12px 34px #28372e38'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>Planen & Bauen</strong><button onClick={()=>{setBuildMode(false);setSelected(null);setOptions([])}} style={btn}>×</button></div>{!selected&&<p style={{fontSize:12,color:'#6e746d'}}>Direkt einen freien Platz in der Landschaft wählen. Das logische Raster bleibt unsichtbar.</p>}{selected&&<small>Position {selected.row}/{selected.col}</small>}{message&&<p style={{fontSize:11}}>{message}</p>}{options.map(o=><div key={o.key} style={{padding:'10px 0',borderTop:'1px solid #ddd'}}><b style={{fontSize:12}}>{o.name}</b><div style={{fontSize:11,color:'#777'}}>{o.displayCost.toLocaleString('de-DE')} Cr</div>{o.knowledgeLocked&&o.learningUrl?<a href={o.learningUrl}>Wissen lernen →</a>:<button disabled={o.knowledgeLocked||o.siteBlocked||building} onClick={()=>void start(o)} style={{...btn,height:28}}>Bauen</button>}</div>)}</aside>}</main>}
