'use client'

import React, { useState } from 'react'
import type { OverlayDef, OverlayMetric, OverlayAlert, OverlayAction } from '@/lib/game/buildings/types'
export type { OverlayDef }

const MONO="'Courier Prime', monospace",SANS='system-ui, sans-serif'
const C={bg:'#f8f5ee',bgAlt:'#f2ede4',bgWhite:'#ffffff',border:'#ddd6c8',borderLight:'#ece8e0',text:'#1a1a18',textMuted:'#6b6357',textFaint:'#9e9485',accent:'#2a4e7a',accentLight:'#e8eef6',gold:'#8a6a00',goldLight:'#faf3e0',green:'#1a7a4a',greenLight:'#e8f7ef',greenBorder:'#a0dcb8',red:'#b52a2a',redLight:'#faeaea',redBorder:'#f0a0a0',orange:'#b54a00',orangeLight:'#faeee8',orangeBorder:'#e8b890'}
const SEVERITY_STYLE:Record<string,{bg:string;border:string;color:string;icon:string}>={critical:{bg:C.redLight,border:C.redBorder,color:C.red,icon:'●'},warning:{bg:C.orangeLight,border:C.orangeBorder,color:C.orange,icon:'▲'},info:{bg:C.accentLight,border:'#b8cce8',color:C.accent,icon:'i'},success:{bg:C.greenLight,border:C.greenBorder,color:C.green,icon:'✓'}}
const TREND_ICON:Record<string,string>={up:'↑',down:'↓',stable:'—',critical:'!'},TREND_COLOR:Record<string,string>={up:C.green,down:C.red,stable:C.textFaint,critical:C.red},SEVERITY_ORDER:Record<string,number>={critical:0,warning:1,info:2,success:3}
function SectionLabel({text}:{text:string}){return <div style={{fontSize:'.63rem',color:C.textFaint,letterSpacing:'.14em',textTransform:'uppercase',fontFamily:MONO,marginBottom:'.5rem'}}>{text}</div>}
function MetricCard({m}:{m:OverlayMetric}){const trendColor=m.trend?(TREND_COLOR[m.trend]??C.accent):C.accent,trendIcon=m.trend?(TREND_ICON[m.trend]??''):'';return <div style={{background:C.bgWhite,border:`1px solid ${C.borderLight}`,borderRadius:9,padding:'.75rem .9rem'}}><div style={{fontSize:'.65rem',color:C.textFaint,letterSpacing:'.1em',textTransform:'uppercase',fontFamily:MONO,marginBottom:5}}>{m.label}</div><div style={{display:'flex',alignItems:'baseline',gap:4}}><span style={{fontSize:'1.2rem',fontWeight:700,color:trendColor,fontFamily:MONO,lineHeight:1}}>{typeof m.value==='number'?m.value.toLocaleString('de'):m.value}</span>{m.unit&&<span style={{fontSize:'.7rem',color:C.textFaint}}>{m.unit}</span>}{trendIcon&&<span style={{fontSize:'.75rem',color:trendColor,marginLeft:2,fontFamily:MONO}}>{trendIcon}</span>}</div>{m.hint&&<div style={{fontSize:'.68rem',color:C.textMuted,marginTop:4,lineHeight:1.4}}>{m.hint}</div>}</div>}
function AlertRow({a}:{a:OverlayAlert}){const s=SEVERITY_STYLE[a.severity]??SEVERITY_STYLE.info;return <div style={{background:s.bg,border:`1px solid ${s.border}`,borderRadius:9,padding:'.7rem .9rem',display:'flex',gap:'.6rem',alignItems:'flex-start'}}><span style={{fontSize:'.75rem',color:s.color,fontFamily:MONO,flexShrink:0,marginTop:2,fontWeight:700}}>{s.icon}</span><span style={{fontSize:'.85rem',color:C.text,lineHeight:1.55,fontFamily:SANS}}>{a.text}</span></div>}
function ActionBtn({a,onAction}:{a:OverlayAction;onAction?:(id:string)=>void}){const activate=()=>{if(a.disabled)return;if(a.href){window.location.assign(a.href);return}onAction?.(a.id)};return <button disabled={a.disabled} onClick={activate} style={{width:'100%',padding:'.75rem 1rem',background:a.disabled?C.bgAlt:a.primary?C.accent:C.bgWhite,color:a.disabled?C.textFaint:a.primary?'#fff':C.text,border:`1px solid ${a.disabled?C.border:a.primary?C.accent:C.border}`,borderRadius:9,cursor:a.disabled?'not-allowed':'pointer',textAlign:'left',fontSize:'.9rem',fontWeight:a.primary?700:500,fontFamily:SANS,opacity:a.disabled?.6:1}}>{a.label}</button>}
export interface BuildingOverlayProps{overlay:OverlayDef;onClose:()=>void;onAction?:(actionId:string)=>void}
export default function BuildingOverlay({overlay,onClose,onAction}:BuildingOverlayProps){const[showInsight,setShowInsight]=useState(false),sortedAlerts=[...overlay.alerts].sort((a,b)=>(SEVERITY_ORDER[a.severity]??9)-(SEVERITY_ORDER[b.severity]??9));return <div style={{position:'fixed',inset:0,zIndex:1050,background:'rgba(2,4,8,.72)',display:'flex',alignItems:'flex-end',justifyContent:'center'}} onClick={e=>e.target===e.currentTarget&&onClose()}><div style={{width:'min(540px,100vw)',background:C.bg,borderRadius:'14px 14px 0 0',maxHeight:'82vh',display:'flex',flexDirection:'column',boxShadow:'0 -4px 32px rgba(0,0,0,.4)'}}><div style={{padding:'1.1rem 1.4rem .85rem',borderBottom:`1px solid ${C.border}`,flexShrink:0,display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div><div style={{fontSize:'1.2rem',fontWeight:700,color:C.text,fontFamily:MONO}}>{overlay.title}</div>{overlay.subtitle&&<div style={{fontSize:'.78rem',color:C.textMuted,marginTop:3,fontFamily:SANS}}>{overlay.subtitle}</div>}</div><button onClick={onClose} style={{background:C.bgAlt,border:`1px solid ${C.border}`,borderRadius:'50%',width:32,height:32,cursor:'pointer',fontSize:'.95rem',color:C.textMuted,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,fontFamily:MONO}}>✕</button></div><div style={{flex:1,overflowY:'auto',padding:'1.1rem 1.4rem 1.5rem'}}>{overlay.metrics.length>0&&<section style={{marginBottom:'1.25rem'}}><SectionLabel text="Was passiert hier?"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'.55rem'}}>{overlay.metrics.map(m=><MetricCard key={m.id} m={m}/>)}</div></section>}{sortedAlerts.length>0&&<section style={{marginBottom:'1.25rem'}}><SectionLabel text="Was fällt auf?"/><div style={{display:'flex',flexDirection:'column',gap:'.45rem'}}>{sortedAlerts.map(a=><AlertRow key={a.id} a={a}/>)}</div></section>}{overlay.actions.length>0&&<section style={{marginBottom:'1.25rem'}}><SectionLabel text="Was kann ich tun?"/><div style={{display:'flex',flexDirection:'column',gap:'.4rem'}}>{overlay.actions.map(a=><ActionBtn key={a.id} a={a} onAction={onAction}/>)}</div></section>}{overlay.insight&&<section><button onClick={()=>setShowInsight(v=>!v)} style={{width:'100%',background:'transparent',border:`1px solid ${C.border}`,borderRadius:9,padding:'.6rem .9rem',cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',fontFamily:SANS}}><span style={{fontSize:'.82rem',color:C.textMuted,fontWeight:700}}>Warum?</span><span style={{fontSize:'.72rem',color:C.textFaint,fontFamily:MONO}}>{showInsight?'▲':'▼'}</span></button>{showInsight&&<div style={{marginTop:'.45rem',padding:'.85rem 1rem',background:C.goldLight,border:`1px solid ${C.gold}44`,borderRadius:9,fontSize:'.85rem',color:C.text,lineHeight:1.75,fontFamily:SANS}}>{overlay.insight}</div>}</section>}</div></div></div>}
