// Scanner domain: Ground Truth, measurement, interpretation and discovery are separate.
export const SCANNER_BASE_RADIUS=4
export interface GridPoint{row:number;col:number}
export interface GroundTruthAnomaly extends GridPoint{id:string;locationSlug:string;kind:'geological_anomaly';strength:number}
export interface ScannerMeasurement{id:string;locationSlug:string;scannerEntityId:string;origin:GridPoint;radius:number;measuredAt:string;coveredCells:GridPoint[];signals:Array<{groundTruthId:string;row:number;col:number;signalClass:'unknown_subsurface';strength:number}>}
export interface ScannerDiscovery extends GridPoint{groundTruthId:string;measurementId:string;interpretation:{measurementId:string;level:'anomaly_only';label:'Geologische Anomalie';confidence:'low'}}
function hashText(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function unit(seed:number){let x=seed>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
export function groundTruthForLocation(locationSlug:string,rows:number,cols:number):GroundTruthAnomaly[]{const s=hashText(`noxia:ground-truth:${locationSlug}`);return[{id:`gt:${locationSlug}:geo:001`,locationSlug,row:Math.min(rows-1,Math.floor(unit(s+101)*rows)),col:Math.min(cols-1,Math.floor(unit(s+211)*cols)),kind:'geological_anomaly',strength:.55+unit(s+307)*.4}]}
export function cellsInRadius(origin:GridPoint,radius:number,rows:number,cols:number){const out:GridPoint[]=[];for(let row=Math.max(0,origin.row-radius);row<=Math.min(rows-1,origin.row+radius);row++)for(let col=Math.max(0,origin.col-radius);col<=Math.min(cols-1,origin.col+radius);col++){const dr=row-origin.row,dc=col-origin.col;if(Math.sqrt(dr*dr+dc*dc)<=radius)out.push({row,col})}return out}
export function runScannerMeasurement(a:{locationSlug:string;scannerEntityId:string;origin:GridPoint;rows:number;cols:number;radius?:number;measuredAt?:string}){const radius=a.radius??SCANNER_BASE_RADIUS,measuredAt=a.measuredAt??new Date().toISOString(),coveredCells=cellsInRadius(a.origin,radius,a.rows,a.cols),covered=new Set(coveredCells.map(c=>`${c.row},${c.col}`)),detected=groundTruthForLocation(a.locationSlug,a.rows,a.cols).filter(x=>covered.has(`${x.row},${x.col}`));const measurement:ScannerMeasurement={id:`measurement:${a.scannerEntityId}:${Date.parse(measuredAt)}`,locationSlug:a.locationSlug,scannerEntityId:a.scannerEntityId,origin:a.origin,radius,measuredAt,coveredCells,signals:detected.map(x=>({groundTruthId:x.id,row:x.row,col:x.col,signalClass:'unknown_subsurface',strength:x.strength}))};const discoveries:ScannerDiscovery[]=detected.map(x=>({groundTruthId:x.id,measurementId:measurement.id,row:x.row,col:x.col,interpretation:{measurementId:measurement.id,level:'anomaly_only',label:'Geologische Anomalie',confidence:'low'}}));return{measurement,discoveries}}
export function mergeDiscoveries(existing:ScannerDiscovery[],incoming:ScannerDiscovery[]){const map=new Map(existing.map(d=>[d.groundTruthId,d]));for(const d of incoming)map.set(d.groundTruthId,d);return[...map.values()]}
