-- Supabase migration-history bridge.
-- This version exists in the production migration history but its historical SQL
-- duplicated the earlier canonical 20260831220000 scanner discovery migration
-- with a divergent shape (no measurement_count, plus an owner-read policy that
-- can never match because grants to anon/authenticated are revoked). The
-- canonical shape is retained in 20260831220000, and 20260902000000 converges
-- databases that recorded this variant. Intentionally no-op: do not remove or
-- repurpose.
