'use client'

import { useEffect, useMemo, useState } from 'react'
import { awarenessConversationForResident } from '@/lib/game/npcAwarenessConversation'
import { residentRoutine, virtualDayProgress } from '@/lib/game/npcDailyRoutine'
import { getStreetTiles, nearestStreetTile } from '@/lib/game/streetTiles'
import { sourceForAwarenessItem, type WorldAwarenessItem } from '@/lib/game/worldAwareness'

type TileEntity = { id:string; entity_id:string; entity_type:string; tile_row:number; tile_col:number; profile_id:string|null }
type Resident = { id:string; displayName:string; activityState:string; assignments?:{type:string;roleCode:string|null;tileEntityId:string|null}[] }
type ResidentPosition = { resident:Resident; col:number; row:number; moving:boolean; activity:string; socialGroup:number }
type ChatEntry = { role:'user'|'assistant'; content:string }
type Props = { locationSlug:string; population:number; entities:TileEntity[]; pending:unknown[]; userId:string }
const COLS=32, ROWS=24, MAX_PLAYER_CHARS=80, PLAYER_JOIN_DISTANCE=1.25
function residentRole(r:Resident){return r.assignments?.find(a=>a.type==='work')?.roleCode??r.activityState??'general'}
function assignment(r:Resident,type:string){return r.assignments?.find(a=>a.type===type)}
function hash(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return((h>>>0)%10000)/10000}
function distance(a:{col:number;row:number},b:{col:number;row:number}){return Math.hypot(a.col-b.col,a.row-b.row)}

export default function ColonyConversationLayer({locationSlug,population,entities,pending,userId}:Props){
 const[residents,setResidents]=useState<Resident[]>([]),[items,setItems]=useState<WorldAwarenessItem[]>([]),[open,setOpen]=useState(false),[tick,setTick]=useState(0),[joining,setJoining]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<ChatEntry[]>([]),[sending,setSending]=useState(false),[chatError,setChatError]=useState('')
 useEffect(()=>{let live=true;Promise.all([fetch(`/api/game/population?locationSlug=${encodeURIComponent(locationSlug)}`).then(r=>r.ok?r.json():{residents:[]}),fetch('/api/game/world-awareness').then(r=>r.ok?r.json():{items:[]})]).then(([p,a])=>{if(!live)return;setResidents(Array.isArray(p.residents)?p.residents:[]);setItems(Array.isArray(a.items)?a.items:[])}).catch(()=>{});return()=>{live=false}},[locationSlug])
 useEffect(()=>{const timer=setInterval(()=>setTick(v=>v+1),450);return()=>clearInterval(timer)},[])
 const buildings=useMemo(()=>entities.filter(e=>e.entity_type==='building'),[entities])
 const streets=useMemo(()=>getStreetTiles(locationSlug,population,entities,pending,userId,COLS,ROWS),[locationSlug,population,entities,pending,userId])
 const communityBuildings=useMemo(()=>{const preferred=['bar','school','habitat','residential_block','admin'];return buildings.filter(b=>preferred.includes(b.entity_id))},[buildings])
 const playerAnchor=useMemo(()=>{const habitat=buildings.find(b=>b.entity_id==='habitat'&&b.profile_id===userId);return nearestStreetTile(habitat?.tile_row??12,habitat?.tile_col??16,streets)},[buildings,userId,streets])
 const positions=useMemo<ResidentPosition[]>(()=>{const dayProgress=virtualDayProgress(tick);const mapped: Array<ResidentPosition|null>=residents.map(resident=>{const routine=residentRoutine(resident.id,dayProgress),workBuilding=buildings.find(b=>b.id===assignment(resident,'work')?.tileEntityId),homeBuilding=buildings.find(b=>b.id===assignment(resident,'home')?.tileEntityId),communityBuilding=communityBuildings.length?communityBuildings[routine.socialGroup%communityBuildings.length]:homeBuilding,targetBuilding=routine.target==='work'?workBuilding:routine.target==='community'?communityBuilding:homeBuilding,anchor=targetBuilding?nearestStreetTile(targetBuilding.tile_row,targetBuilding.tile_col,streets):null;if(!anchor)return null;let col=anchor.col,row=anchor.row;if(!routine.moving){const angle=hash(`${resident.id}:group-angle`)*Math.PI*2,radius=routine.target==='community'?.08+hash(`${resident.id}:group-radius`)*.18:.08+hash(`${resident.id}:local-radius`)*.22;col+=Math.cos(angle)*radius;row+=Math.sin(angle)*radius}return{resident,col,row,moving:routine.moving,activity:routine.activity,socialGroup:routine.socialGroup}});return mapped.filter((value):value is ResidentPosition=>value!==null)},[residents,buildings,communityBuildings,streets,tick])
 const scene=useMemo(()=>{if(items.length<1)return null;const candidates=positions.filter(p=>!p.moving&&(p.activity==='meal'||p.activity==='community'));let best:{first:ResidentPosition;second:ResidentPosition;score:number}|null=null;for(let i=0;i<candidates.length;i++)for(let j=i+1;j<candidates.length;j++){const first=candidates[i],second=candidates[j],d=distance(first,second);if(d>.65)continue;const score=d+(first.socialGroup===second.socialGroup?-.25:0)+(playerAnchor&&Math.min(distance(first,playerAnchor),distance(second,playerAnchor))<=PLAYER_JOIN_DISTANCE?-.2:0);if(!best||score<best.score)best={first,second,score}}if(!best)return null;const dayKey=new Date().toISOString().slice(0,10),conversation=awarenessConversationForResident(best.first.resident.id,residentRole(best.first.resident),items,dayKey);if(!conversation)return null;const playerDistance=playerAnchor?Math.min(distance(best.first,playerAnchor),distance(best.second,playerAnchor)):Infinity;return{first:best.first.resident,second:best.second.resident,conversation,source:sourceForAwarenessItem(conversation.item),sameGroup:best.first.socialGroup===best.second.socialGroup,playerNearby:playerDistance<=PLAYER_JOIN_DISTANCE}},[positions,items,playerAnchor])
 useEffect(()=>{if(!scene){setOpen(false);setJoining(false);setHistory([]);return}setHistory([]);setJoining(false);setChatError('')},[scene?.first.id,scene?.second.id,scene?.conversation.item.id])
 async function sendMessage(){if(!scene||!scene.playerNearby||sending)return;const player=message.trim().slice(0,MAX_PLAYER_CHARS);if(!player)return;setSending(true);setChatError('');try{const response=await fetch('/api/game/npc-conversation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player,npcName:scene.first.displayName,npcRole:residentRole(scene.first),headline:scene.conversation.item.title,source:scene.source?.name??scene.conversation.item.sourceId,history})}),data=await response.json().catch(()=>({}));if(!response.ok||!data.reply)throw new Error(data.error||'conversation_failed');setHistory(current=>[...current,{role:'user' as const,content:player},{role:'assistant' as const,content:String(data.reply)}].slice(-6));setMessage('')}catch(error){const code=error instanceof Error?error.message:'';setChatError(code==='conversation_provider_unavailable'?'DeepSeek ist noch nicht konfiguriert.':'Gespräch derzeit nicht erreichbar.')}finally{setSending(false)}}
 if(!scene)return null
 return <div style={{position:'absolute',zIndex:118,left:16,bottom:70,width:open?370:285,fontFamily:'system-ui',color:'#e8f0f5'}}><button onClick={()=>setOpen(v=>!v)} style={{width:'100%',textAlign:'left',border:'1px solid #45657c',borderRadius:open?'9px 9px 0 0':9,background:'#091925ee',color:'#e8f0f5',padding:'9px 11px',cursor:'pointer'}}><small style={{color:'#79a6c7',letterSpacing:'.1em'}}>{scene.playerNearby?'GESPRÄCH IN HÖRWEITE · ERDE':'GESPRÄCH IN DER NÄHE · ERDE'}</small><br/><b>{scene.first.displayName} + {scene.second.displayName}</b><div style={{marginTop:2,color:'#8fa3b1',fontSize:9}}>{scene.sameGroup?'gleicher Sozialkreis · ':''}{scene.playerNearby?'du kannst dich einmischen':'räumliche Begegnung'}</div></button>{open&&<div style={{border:'1px solid #45657c',borderTop:0,borderRadius:'0 0 9px 9px',background:'#071421f2',padding:11,fontSize:12,lineHeight:1.5}}><p style={{margin:'0 0 8px'}}><b>{scene.first.displayName}:</b> „{scene.conversation.opener}“</p><p style={{margin:'0 0 9px',color:'#c8d5dd'}}><b>{scene.second.displayName}:</b> „{scene.conversation.followUp}“</p>{history.map((entry,index)=><p key={`${entry.role}-${index}`} style={{margin:'6px 0',color:entry.role==='assistant'?'#d9e6ec':'#f1d57a'}}><b>{entry.role==='assistant'?scene.first.displayName:'Du'}:</b> „{entry.content}“</p>)}{scene.playerNearby&&!joining&&<button onClick={()=>setJoining(true)} style={{width:'100%',margin:'7px 0',padding:'8px 10px',border:'1px solid #3976a5',borderRadius:6,background:'#0a3150',color:'#fff',fontWeight:800,cursor:'pointer'}}>ANSPRECHEN</button>}{scene.playerNearby&&joining&&<div style={{marginTop:8}}><div style={{display:'flex',gap:6}}><input value={message} maxLength={MAX_PLAYER_CHARS} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sendMessage()}} placeholder="Kurze Antwort …" disabled={sending} style={{flex:1,minWidth:0,padding:'8px 9px',border:'1px solid #45657c',borderRadius:6,background:'#06111a',color:'#eef5f8'}}/><button onClick={()=>void sendMessage()} disabled={sending||!message.trim()} style={{border:'1px solid #3976a5',borderRadius:6,background:'#0a3150',color:'#fff',padding:'0 10px',cursor:sending?'wait':'pointer'}}>{sending?'…':'Senden'}</button></div><div style={{marginTop:3,textAlign:'right',color:message.length>=70?'#f1d57a':'#738795',fontSize:9}}>{message.length}/{MAX_PLAYER_CHARS}</div>{chatError&&<div style={{marginTop:5,color:'#e29a86',fontSize:10}}>{chatError}</div>}</div>}<div style={{marginTop:8,color:'#8fa3b1',fontSize:10}}>Reale Meldung: {scene.source?.name??scene.conversation.item.sourceId}. Die Reaktionen der Bewohner sind fiktional.</div><a href={scene.conversation.item.url} target="_blank" rel="noreferrer" style={{display:'inline-block',marginTop:7,color:'#f1d57a',fontSize:10}}>Originalquelle öffnen ↗</a></div>}</div>
}
