'use client'

import { useEffect, useMemo, useState } from 'react'
import { useGameStore } from '@/lib/store/gameStore'
import { getSessionInfo } from '@/lib/supabase/auth'
import WalkableColony from './WalkableColony'
import ColonyHudOverlay, { ColonyHudStyles } from './ColonyHudOverlay'
import WorldAwarenessTicker from './WorldAwarenessTicker'
import ColonyConversationLayer from './ColonyConversationLayer'

type WorldLocation={id:string;slug:string;name?:string;location_type?:string;population?:number;location_resources?:any[]}
type Building={id:string;entity_id:string;entity_type:string;tile_row:number;tile_col:number;profile_id:string|null;owner_class?:string}
const chrome=<style>{`.noxia-primary-colony{position:fixed;z-index:900;left:.65rem;right:.65rem;top:112px;bottom:.65rem;border:1px solid #263f55;border-radius:8px;overflow:hidden;background:#081019 url('/assets/environments/mars/terrain-tharsis.webp') center/cover no-repeat;box-shadow:0 12px 34px rgba(7,14,23,.32)}.noxia-return-colony{position:fixed;z-index:1180;left:50%;top:102px;transform:translateX(-50%);border:1px solid #2c78b6;border-radius:7px;background:#08243b;color:#e7f3fb;font:700 11px system-ui;padding:7px 11px;cursor:pointer}.noxia-interior{position:absolute;inset:0;z-index:130;background:linear-gradient(180deg,#05101c33,#05101cd9),url('/assets/buildings/habitat/mars/interior-main.webp') center/cover no-repeat;color:#edf5fa;font-family:system-ui}.noxia-interior-head{position:absolute;left:18px;right:18px;top:18px;display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border:1px solid #38546c;border-radius:9px;background:#071421e8}.noxia-interior-head small{display:block;color:#79a6c7;font-size:9px;letter-spacing:.14em}.noxia-interior-head b{font-size:17px}.noxia-interior-head button{border:1px solid #3976a5;border-radius:7px;background:#0a3150;color:#fff;padding:8px 12px;font-weight:800;cursor:pointer}.noxia-interior-card{position:absolute;left:22px;bottom:22px;width:280px;padding:14px;border:1px solid #35536c;border-radius:9px;background:#071421e8}.noxia-interior-card h3{margin:0 0 7px}.noxia-interior-card p{margin:0;color:#b7c8d4;font-size:11px;line-height:1.55}@media(max-width:900px){.noxia-primary-colony{top:120px}}`}</style>
export default function DashboardPrimaryColony(){
 const location=useGameStore(s=>s.location),[planning,setPlanning]=useState(false),[userId,setUserId]=useState(''),[locations,setLocations]=useState<WorldLocation[]>([]),[entities,setEntities]=useState<any[]>([]),[builds,setBuilds]=useState<any[]>([]),[interior,setInterior]=useState<Building|null>(null)
 useEffect(()=>{setPlanning(false);setInterior(null)},[location]);useEffect(()=>{let live=true;let timer:ReturnType<typeof setInterval>|undefined;async function refresh(){try{const{token,userId:uid}=await getSessionInfo();const[br,wr]=await Promise.all([fetch('/api/game/build',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}),fetch('/api/game/world',{cache:'no-store'})]);if(!live)return;if(br.ok){const d=await br.json();setUserId(uid);setEntities(Array.isArray(d.entities)?d.entities:[]);setBuilds(Array.isArray(d.builds)?d.builds:[])}if(wr.ok){const d=await wr.json();setLocations(Array.isArray(d.locations)?d.locations:[])}}catch{}}refresh();timer=setInterval(refresh,30000);return()=>{live=false;if(timer)clearInterval(timer)}},[location])
 const current=locations.find(l=>l.slug===location),isStation=current?.location_type==='station'||location==='prometheus',localEntities=useMemo(()=>!current?[]:entities.filter((e:any)=>e.locations?.slug===location||e.location_id===current.id),[entities,current,location]),localBuilds=useMemo(()=>!current?[]:builds.filter((b:any)=>b.locations?.slug===location||b.location_id===current.id),[builds,current,location])
 if(!current||isStation||!userId)return null;if(planning)return <>{chrome}<button className="noxia-return-colony" onClick={()=>setPlanning(false)}>◈ Kolonieansicht</button></>
 return <>{chrome}<ColonyHudStyles/><div className="noxia-primary-colony"><WalkableColony locationSlug={location} locationName={current.name??location} population={current.population??0} entities={localEntities} pending={localBuilds} ships={[]} locationId={current.id} userId={userId} onClose={()=>setPlanning(true)} onEnterBuilding={b=>setInterior(b)}/><WorldAwarenessTicker/><ColonyConversationLayer locationSlug={location}/><ColonyHudOverlay current={current} builds={localBuilds} entityCount={localEntities.length} onPlan={()=>setPlanning(true)}/>{interior&&<div className="noxia-interior"><div className="noxia-interior-head"><div><small>INNENRAUM · THARSIS HUB</small><b>{interior.entity_id==='habitat'?'Habitat · Gemeinschaftsmodul':'Anlageninnenraum'}</b></div><button onClick={()=>setInterior(null)}>← Zur Kolonie</button></div><div className="noxia-interior-card"><h3>{interior.entity_id==='habitat'?'Persönliche Ebene':'Technischer Innenraum'}</h3><p>{interior.entity_id==='habitat'?'Aufenthalt, Pflanzen, Arbeitsplätze und Bewohner machen die Kolonie hier als Lebensraum erfahrbar.':'Diese Anlage nutzt vorerst den gemeinsamen Innenraum-Fallback; eigene technische Innenräume folgen als Asset-Slices.'}</p></div></div>}</div></>
}
