'use client'

// StationOverlay.tsx
// Aktualisiert: 11.09.2026 — Stationsrollen/Free-Port-Semantik sichtbar gemacht
// Version:      0.5.0
//
// Raumstations-Ansicht für L4/L5-Stationen und Orbit-Stationen.

import { useState, useEffect, useCallback } from 'react'
import { useGameStore } from '@/lib/store/gameStore'
import { STATION_MODULE_DEFS as MODULE_DEFS, BUILDABLE_STATION_MODULES as BUILDABLE_MODULES } from '@/lib/game/stationModules'
import { getStationServiceProfile } from '@/lib/game/stationProfiles'

interface StationModule { id:string;entity_id:string;condition:number;status:string;profile_id:string|null;owner_class?:string }
interface StationOverlayProps { slug:string;name:string;population:number;populationMax:number;userId:string;locationId:string;locationResources:{resource:string;stock:number;consumption:number}[];credits:number;entities:StationModule[];onChanged:()=>void;onOpenWarehouse?:()=>void;onOpenMarket?:()=>void }
const DARK='#07111b',MONO='monospace',RES_ICON:Record<string,string>={water:'💧',energy:'⚡',metal:'⛏️',components:'⚙️'},RES_LABEL:Record<string,string>={water:'Wasser',energy:'Energie',metal:'Metall',components:'Bauteile'}
function stockColor(stock:number,consumption:number){return stock<=Math.max(10,consumption*2)?'#e87070':stock<=Math.max(30,consumption*5)?'#e0b060':'#83c99a'}
function ModuleRing({modules,selected,onSelect,userId,onOpenWarehouse}:{modules:StationModule[];selected:string|null;onSelect:(id:string)=>void;userId:string;onOpenWarehouse?:()=>void}){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8,marginBottom:16}}>{modules.map(m=>{const d=MODULE_DEFS[m.entity_id],own=m.profile_id===userId,state=m.owner_class==='STATE';return <button key={m.id} onClick={()=>m.entity_id==='warehouse'&&onOpenWarehouse?onOpenWarehouse():onSelect(m.id)} style={{padding:12,textAlign:'left',background:selected===m.id?'#173047':'#0a1824',border:`1px solid ${own?'#c9a961':state?'#5aaeff':'#294052'}`,color:'#d6e2ec',borderRadius:8,cursor:'pointer'}}><div>{d?.icon??'◆'} <b>{d?.label??m.entity_id}</b></div><small style={{color:'#7e94a7'}}>{m.condition}% · {m.status}</small></button>})}</div>}
function ModuleDetail({module,userId,onClose,onSell}:{module:StationModule;userId:string;onClose:()=>void;credits:number;onSell:(id:string)=>void}){const def=MODULE_DEFS[module.entity_id],isOwn=module.profile_id===userId,isState=module.owner_class==='STATE',condColor=module.condition<40?'#e87070':module.condition<70?'#e0b060':'#83c99a';return <div style={{background:'#0a1520',border:'1px solid #1e3a52',borderRadius:8,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{color:'#c9a961'}}>{def?.icon} {def?.label??module.entity_id}</strong><button onClick={onClose}>×</button></div><p style={{color:'#8aa0b5',fontSize:12}}>{def?.description}</p><div style={{color:condColor,fontFamily:MONO,fontSize:12}}>Zustand: {module.condition}% · {module.status}</div><div style={{color:'#64788a',fontSize:11,marginTop:8}}>{isState?'Staatseigentum':isOwn?'Dein Modul':'Fremdeigentum'}</div>{isOwn&&!isState&&<button onClick={()=>onSell(module.id)} style={{marginTop:12}}>Verkaufen</button>}</div>}
function ServiceCard({label,detail,active=true}:{label:string;detail:string;active?:boolean}){return <div style={{background:'#091723',border:'1px solid #20384b',borderRadius:7,padding:'8px 10px',minWidth:135,opacity:active?1:.45}}><div style={{fontSize:10,fontFamily:MONO,color:active?'#c9a961':'#64788a',letterSpacing:'.08em'}}>{label}</div><div style={{fontSize:11,color:'#8aa0b5',marginTop:3}}>{detail}</div></div>}

export default function StationOverlay(props:StationOverlayProps){
 const{slug,name,population,populationMax,userId,locationResources,credits,entities,onChanged,onOpenWarehouse,onOpenMarket}=props
 const[selected,setSelected]=useState<string|null>(null),[building,setBuilding]=useState(false),[msg,setMsg]=useState('')
 const loadFromServer=useGameStore(s=>s.loadFromServer)
 const stationProfile=getStationServiceProfile(slug)
 const depotLabel=stationProfile.depotMode==='persistent-node'?'Depot':'Lager'
 const marketLabel=stationProfile.marketMode==='local-node'?'Markt':'Handel'
 useEffect(()=>{if(selected&&!entities.some(e=>e.id===selected))setSelected(null)},[entities,selected])
 const refresh=useCallback(async()=>{await loadFromServer();onChanged()},[loadFromServer,onChanged])
 const build=useCallback(async(moduleId:string)=>{setBuilding(true);setMsg('');try{const sb=(await import('@/lib/supabase/client')).createClient();const{data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Bitte melde dich erneut an.');const params=new URLSearchParams({action:'start',buildableId:moduleId,location:slug,tileRow:'0',tileCol:'0',tileLevel:'0'});const r=await fetch(`/api/game/build?${params}`,{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error??'Bau fehlgeschlagen');setMsg('Modulbau gestartet.');await refresh()}catch(e){setMsg(e instanceof Error?e.message:'Bau fehlgeschlagen')}finally{setBuilding(false)}},[slug,refresh])
 const sell=useCallback(async(id:string)=>{try{const sb=(await import('@/lib/supabase/client')).createClient();const{data:{session}}=await sb.auth.getSession();if(!session){setMsg('Bitte melde dich erneut an.');return}const r=await fetch(`/api/game/build?action=sell&entityId=${encodeURIComponent(id)}&mode=instant`,{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok){setMsg(d.error??'Verkauf fehlgeschlagen');return}setSelected(null);await refresh()}catch(e){setMsg(e instanceof Error?e.message:'Verkauf fehlgeschlagen')}},[refresh])
 const selectedModule=entities.find(e=>e.id===selected)
 return <div style={{color:'#d6e2ec',background:DARK,minHeight:'100%',padding:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><h2 style={{margin:0,color:'#c9a961'}}>{name}</h2><small>{slug.toUpperCase()} · {stationProfile.roleLabel} · {population}/{populationMax}</small></div><div style={{display:'flex',gap:8,alignItems:'center'}}>{onOpenWarehouse&&stationProfile.depotMode!=='none'&&<button onClick={onOpenWarehouse}>{depotLabel}</button>}{onOpenMarket&&stationProfile.marketMode!=='none'&&<button onClick={onOpenMarket}>{marketLabel}</button>}<strong>{credits.toLocaleString('de-DE')} Cr</strong></div></div><div style={{marginTop:12,padding:'10px 12px',background:stationProfile.freePort?'#101d24':'#0a1520',border:`1px solid ${stationProfile.freePort?'#806f46':'#1e3a52'}`,borderRadius:8}}><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:8}}>{stationProfile.freePort&&<span style={{fontSize:10,fontFamily:MONO,color:'#e2c978',border:'1px solid #806f46',borderRadius:10,padding:'2px 7px'}}>FREE PORT</span>}<span style={{fontSize:10,fontFamily:MONO,color:'#7fb8de'}}>DOCKING ≠ CARGO TRANSFER</span></div><div style={{fontSize:12,color:'#8aa0b5',lineHeight:1.45}}>{stationProfile.summary}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:10}}><ServiceCard label="DOCKING" detail="physische Verbindung" active={stationProfile.docking}/><ServiceCard label="CARGO" detail="expliziter Transfer" active={stationProfile.cargoTransfer}/><ServiceCard label="DEPOT" detail={stationProfile.depotMode==='persistent-node'?'persistenter Knoten':'Stationslager'} active={stationProfile.depotMode!=='none'}/><ServiceCard label="MARKET" detail={stationProfile.marketMode==='local-node'?'lokaler Knotenmarkt':'Stationshandel'} active={stationProfile.marketMode!=='none'}/><ServiceCard label="ONWARD" detail="Weitertransport" active={stationProfile.onwardTransfer}/></div></div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 300px',gap:20,marginTop:16}}><div><ModuleRing modules={entities} selected={selected} onSelect={setSelected} userId={userId} onOpenWarehouse={onOpenWarehouse}/><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{locationResources.map(r=><span key={r.resource} style={{color:stockColor(r.stock,r.consumption)}}>{RES_ICON[r.resource]??'◆'} {RES_LABEL[r.resource]??r.resource}: {r.stock.toFixed(0)}</span>)}</div></div><div>{selectedModule?<ModuleDetail module={selectedModule} userId={userId} onClose={()=>setSelected(null)} credits={credits} onSell={sell}/>:<div><h3>Stationsmodule</h3>{BUILDABLE_MODULES.map(([id,def])=><button key={id} disabled={building||credits<def.cost} onClick={()=>build(id)} style={{display:'block',width:'100%',marginBottom:6,textAlign:'left'}}>{def.icon} {def.label} · {def.cost.toLocaleString('de-DE')} Cr</button>)}{msg&&<p>{msg}</p>}</div>}</div></div></div>
}
