'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { getToken } from '@/lib/supabase/auth'
import BuildingOverlayShell from './BuildingOverlayShell'

type Inventory={id:string;label:string;inventory_kind:string;subject_type:string;subject_id:string|null;metadata?:Record<string,unknown>|null}
type TransportJob={id:string;domain:string;source_inventory_id:string;destination_inventory_id:string;vehicle_role:string|null;resource:string;amount:number;status:string}
type Prospect={id:string;resourceType:string;xM:number;yM:number;abundance:number|null;tier:string|null;confidence:string|null;discoveredAt:string|null;sampledAt:string|null;cacheInventoryId:string|null;sampleAvailable:boolean}
type Props={locationSlug:string;locationName:string;onClose:()=>void}
const ACTIVE=new Set(['reserved','loading','in_transit','arrived','unloading'])
const statusLabel=(s:string)=>s.replaceAll('_',' ')

export default function SurfaceLogisticsOverlay({locationSlug,locationName,onClose}:Props){
 const [inventories,setInventories]=useState<Inventory[]>([]),[jobs,setJobs]=useState<TransportJob[]>([]),[locationId,setLocationId]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[operationMessage,setOperationMessage]=useState<string|null>(null),[discoveries,setDiscoveries]=useState<Prospect[]>([])
 const phobos=locationSlug==='phobos'
 const load=useCallback(async()=>{const token=await getToken();if(!token)throw new Error('Nicht angemeldet');const headers={Authorization:`Bearer ${token}`};const s=await fetch(`/api/game/build/spatial?location=${encodeURIComponent(locationSlug)}`,{headers,cache:'no-store'}),sp=await s.json();if(!s.ok||!sp?.location?.id)throw new Error(sp?.error??'Standort nicht verfügbar');const r=await fetch(`/api/game/logistics?locationId=${encodeURIComponent(sp.location.id)}`,{headers,cache:'no-store'}),lp=await r.json();if(!r.ok)throw new Error(lp?.error??'Logistik nicht verfügbar');setLocationId(sp.location.id);setInventories(Array.isArray(lp.inventories)?lp.inventories:[]);setJobs(Array.isArray(lp.jobs)?lp.jobs:[]);if(phobos){const p=await fetch('/api/game/phobos/prospect',{headers,cache:'no-store'}),pp=await p.json();if(p.ok)setDiscoveries(Array.isArray(pp.discoveries)?pp.discoveries:[])}setError(null)},[locationSlug,phobos])
 useEffect(()=>{let cancelled=false;(async()=>{try{await load()}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[load])
 const byId=useMemo(()=>new Map(inventories.map(i=>[i.id,i])),[inventories]),active=useMemo(()=>jobs.filter(j=>j.domain==='surface'&&ACTIVE.has(j.status)),[jobs]),nodes=useMemo(()=>inventories.filter(i=>i.inventory_kind!=='vehicle'),[inventories])
 const anchor=useMemo(()=>inventories.find(i=>i.metadata?.role==='stickney_anchor_field')??null,[inventories]),depot=useMemo(()=>inventories.find(i=>i.metadata?.role==='stickney_depot')??null,[inventories])
 const completedStickneyRun=useMemo(()=>jobs.some(j=>j.domain==='surface'&&j.status==='completed'&&j.vehicle_role==='Tether Rover 01'&&j.resource!=='research_sample'),[jobs])
 const completedSampleReturn=useMemo(()=>jobs.some(j=>j.domain==='surface'&&j.status==='completed'&&j.vehicle_role==='Tether Rover 01'&&j.resource==='research_sample'),[jobs])
 const activeSampleReturn=useMemo(()=>jobs.some(j=>j.domain==='surface'&&ACTIVE.has(j.status)&&j.resource==='research_sample'),[jobs])

 const runSupply=async()=>{if(!anchor||!depot||!locationId){setOperationMessage('Stickney-Cargoknoten sind noch nicht vollständig bereit.');return}setBusy(true);setOperationMessage(null);try{const token=await getToken();if(!token)throw new Error('Nicht angemeldet');const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};const created=await fetch('/api/game/logistics',{method:'POST',headers,body:JSON.stringify({action:'create-job',locationId,domain:'surface',sourceInventoryId:anchor.id,destinationInventoryId:depot.id,vehicleRole:'Tether Rover 01',resource:'components',amount:6,routeSnapshot:{passable:true,etaSeconds:90,routeKind:'anchor-tether',points:[{xM:90,yM:-60},{xM:48,yM:-26},{xM:22,yM:2}]}})});const cp=await created.json();if(!created.ok||!cp?.job?.id)throw new Error(cp?.error??'Transportauftrag konnte nicht angelegt werden');for(const action of ['begin-loading','start-job']){const res=await fetch('/api/game/logistics',{method:'POST',headers,body:JSON.stringify({action,jobId:cp.job.id})});const payload=await res.json();if(!res.ok)throw new Error(payload?.error??'Transport konnte nicht gestartet werden')}setOperationMessage('Tether Rover 01 fährt 6 Komponenten vom Anchor Field zum Base-Alpha-Depot. Die Route und Roverposition sind auf der Karte sichtbar.');await load()}catch(e){setOperationMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const prospect=async()=>{setBusy(true);setOperationMessage(null);try{const token=await getToken();if(!token)throw new Error('Nicht angemeldet');const res=await fetch('/api/game/phobos/prospect',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'scan',xM:180,yM:90,radiusM:140})});const payload=await res.json();if(!res.ok)throw new Error(payload?.error??'Prospektion fehlgeschlagen');setOperationMessage(payload.newlyDiscovered?.length?`${payload.newlyDiscovered.length} neues Stickney-Vorkommen entdeckt. Der Fund erscheint jetzt als Prospektionsknoten auf der Karte.`:'Kein neuer Treffer. Der Bereich kann erneut untersucht werden.');await load()}catch(e){setOperationMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const collectSample=async(prospect:Prospect)=>{setBusy(true);setOperationMessage(null);try{const token=await getToken();if(!token)throw new Error('Nicht angemeldet');const res=await fetch('/api/game/phobos/prospect',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'collect-sample',prospectId:prospect.id})});const payload=await res.json();if(!res.ok)throw new Error(payload?.error??'Probe konnte nicht entnommen werden');setOperationMessage('Referenzprobe im Feldcache gesichert. Sie kann jetzt mit Tether Rover 01 zu Base Alpha zurückgebracht werden.');await load()}catch(e){setOperationMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const returnSample=async(prospect:Prospect)=>{setBusy(true);setOperationMessage(null);try{const token=await getToken();if(!token)throw new Error('Nicht angemeldet');const res=await fetch('/api/game/phobos/prospect',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'return-sample',prospectId:prospect.id})});const payload=await res.json();if(!res.ok)throw new Error(payload?.error??'Probenrücktransport konnte nicht gestartet werden');setOperationMessage(`Tether Rover 01 bringt die Referenzprobe zum Base-Alpha-Depot (${payload.etaSeconds??'?'} s). Route und Fahrzeug bewegen sich jetzt auf der Karte.`);await load()}catch(e){setOperationMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}

 return <BuildingOverlayShell eyebrow="GEBÄUDE · LOGISTIKZENTRUM" title={locationName} subtitle="Oberflächentransporte, Lager- und Übergabepunkte" onClose={onClose} footer="NOXIA · gemeinsamer Logistics-Core für planetare Standorte">
   <div className="summary"><div><b>{active.length}</b><span>aktive Transporte</span></div><div><b>{nodes.length}</b><span>Logistikknoten</span></div><div><b>{jobs.length}</b><span>Aufträge gesamt</span></div></div>
   {loading&&<div className="state">Logistikdaten werden geladen …</div>}{error&&<div className="state error">{error}</div>}
   {!loading&&!error&&<>{phobos&&<section className="ops"><small>STICKNEY · BASE ALPHA</small><h3>Oberflächeneinsatz</h3><p className="copy">Mikrogravitation bedeutet hier: Andocken und verankern statt landen. Fracht und wissenschaftliche Proben laufen über Tether-Routen; aktive Rover werden auf der gemeinsamen Oberflächenkarte bewegt dargestellt.</p><div className="actions"><button disabled={busy||!anchor||!depot} onClick={runSupply}>Tether-Versorgung starten</button><button disabled={busy} onClick={prospect}>Nordost-Sektor prospektieren</button></div>{operationMessage&&<div className="state opmsg">{operationMessage}</div>}<div className="mission"><b>Mission · Stickney-Einsatz</b><span className={completedStickneyRun?'done':''}>{completedStickneyRun?'✓':'○'} Versorgungstransport abschließen</span><span className={discoveries.length?'done':''}>{discoveries.length?'✓':'○'} Erstes Vorkommen erfassen</span><span className={completedSampleReturn?'done':''}>{completedSampleReturn?'✓':activeSampleReturn?'◉':'○'} Referenzprobe zu Base Alpha bringen</span></div>{discoveries.length>0&&<div className="nodes">{discoveries.map(d=><article key={d.id} className="prospect"><strong>{d.resourceType}</strong><span>{d.tier??'unbekannt'} · Vertrauen {d.confidence??'n/a'}</span><p>{Math.round(d.xM)} m E / {Math.round(d.yM)} m N{d.abundance!=null?` · Index ${d.abundance.toFixed(2)}`:''}</p><div className="sample-actions">{!d.sampledAt&&<button disabled={busy} onClick={()=>collectSample(d)}>Referenzprobe entnehmen</button>}{d.sampledAt&&d.sampleAvailable&&<button disabled={busy||activeSampleReturn} onClick={()=>returnSample(d)}>Probe zu Base Alpha bringen</button>}{d.sampledAt&&!d.sampleAvailable&&<em>{completedSampleReturn?'Probe im Base-Alpha-Depot':'Probe nicht mehr im Feldcache'}</em>}</div></article>)}</div>}</section>}<section><small>TRANSPORTE</small><h3>Aktive Oberflächenlogistik</h3>{!active.length&&<div className="state">Aktuell fährt kein Oberflächentransport.</div>}{active.map(j=><article key={j.id}><div><strong>{j.vehicle_role??'Surface-Fahrzeug'}</strong><span>{statusLabel(j.status)}</span></div><b>{j.amount} {j.resource}</b><p>{byId.get(j.source_inventory_id)?.label??'Quelle'} → {byId.get(j.destination_inventory_id)?.label??'Ziel'}</p></article>)}</section><section><small>KNOTEN</small><h3>Lokale Lager- und Übergabepunkte</h3><div className="nodes">{nodes.map(n=><article key={n.id}><strong>{n.label}</strong><span>{n.subject_type}</span></article>)}</div></section></>}
   <style jsx>{`.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:16px}.summary div,article,.state,.mission{padding:11px 12px;border:1px solid #d2d0c4;border-radius:8px;background:#fffdf7}.summary b{display:block;font-size:22px;color:#315968}.summary span,section small,article span,.mission span{font-size:9px;color:#7b878a}.summary span{text-transform:uppercase}section{margin-top:16px}section small{color:#9a7a26;font-weight:800;letter-spacing:.12em}h3{margin:3px 0 8px;font-size:15px}.state.error{background:#f7e5dc;color:#7f4a35}.state.opmsg{margin-top:8px;background:#f4f0df}.nodes{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}article{margin-top:8px}article>div{display:flex;justify-content:space-between;gap:12px}article p,.copy{margin:4px 0 0;color:#718085;font-size:10px}.actions,.sample-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.actions button,.sample-actions button{border:1px solid #8d7b55;background:#efe6cd;color:#4f442c;border-radius:7px;padding:8px 11px;font:700 10px/1 system-ui;cursor:pointer}.actions button:disabled,.sample-actions button:disabled{opacity:.45;cursor:not-allowed}.sample-actions em{font-size:9px;color:#52724c;font-style:normal}.mission{display:grid;gap:5px;margin-top:9px}.mission b{font-size:11px;color:#315968}.mission .done{color:#52724c}.prospect{border-color:#b5a472;background:#fffaf0}@media(max-width:700px){.summary{grid-template-columns:1fr}}`}</style>
 </BuildingOverlayShell>
}
