'use client'
// app/dashboard/WalkableColony.tsx
// Strategische Kolonieansicht mit sichtbarer Living Population.

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { getStreetTiles } from '@/lib/game/streetTiles'

interface TileEntity { id:string; entity_id:string; entity_type:string; tile_row:number; tile_col:number; profile_id:string|null; owner_class:string; actor_name?:string|null; username?:string|null }
interface Ship { id:string; ship_type:string; is_active:boolean; location_id:string }
interface Assignment { type:string; roleCode:string|null; tileEntityId:string|null }
interface Resident { id:string; displayName:string; birthYear:number|null; activityState:string; lastAction:string|null; assignments:Assignment[]; needs:{code:string;satisfaction:number}[]; skills:{code:string;level:number;experience:number}[] }
interface Props { locationSlug:string; locationName:string; population:number; entities:TileEntity[]; pending:any[]; ships:Ship[]; locationId:string; userId:string; onClose:()=>void; onEnterBuilding?:(entity:TileEntity)=>void }

const COLS=32, ROWS=24, ISO_W=32, ISO_H=16, BLOCK_H=26
const CANVAS_W=(COLS+ROWS)*ISO_W+100, CANVAS_H=(COLS+ROWS)*ISO_H+200, VP_W=800, VP_H=500, MIN_ZOOM=.65, MAX_ZOOM=1.65
function isoProject(col:number,row:number){return{x:(col-row)*ISO_W+CANVAS_W/2,y:(col+row)*ISO_H+60}}
const C={road:'#5a5040',roadMain:'#6a6050',crossing:'#7a7060',habitat:'#4a6e5a',state:'#3a5a6e',corp:'#6e4a2a',figure:'#c9a961',npc:'#9cc9b2',ship:'#6a9aca',text:'#d4c8b0'}
function drawFigure(ctx:CanvasRenderingContext2D,x:number,y:number,color=C.figure,label=''){ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(x,y+3,9,4,0,0,Math.PI*2);ctx.fill();const b=y-4;ctx.fillStyle='#1a2a3a';ctx.fillRect(x-4,b-8,3.5,8);ctx.fillRect(x+1,b-8,3.5,8);ctx.fillStyle='#2a4e7a';ctx.fillRect(x-5,b-18,10,11);ctx.fillRect(x-8,b-17,3.5,8);ctx.fillRect(x+5,b-17,3.5,8);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,b-22,6,0,Math.PI*2);ctx.fill();if(label){ctx.fillStyle=C.text;ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText(label,x,b-32)}}
function drawIsoFloor(ctx:CanvasRenderingContext2D,col:number,row:number,color:string){const{x,y}=isoProject(col,row);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y-ISO_H);ctx.lineTo(x+ISO_W,y);ctx.lineTo(x,y+ISO_H);ctx.lineTo(x-ISO_W,y);ctx.closePath();ctx.fill()}
function drawIsoBuilding(ctx:CanvasRenderingContext2D,col:number,row:number,topColor:string,label?:string,icon?:string,height=BLOCK_H){const{x,y}=isoProject(col,row),topY=y-height;const shade=(hex:string,f:number)=>{const c=hex.replace('#','');const n=(i:number)=>Math.max(0,Math.min(255,parseInt(c.slice(i,i+2),16)*f))|0;return`rgb(${n(0)},${n(2)},${n(4)})`};ctx.fillStyle=shade(topColor,.55);ctx.beginPath();ctx.moveTo(x-ISO_W,y);ctx.lineTo(x,y+ISO_H);ctx.lineTo(x,y+ISO_H-height);ctx.lineTo(x-ISO_W,y-height);ctx.closePath();ctx.fill();ctx.fillStyle=shade(topColor,.75);ctx.beginPath();ctx.moveTo(x,y+ISO_H);ctx.lineTo(x+ISO_W,y);ctx.lineTo(x+ISO_W,y-height);ctx.lineTo(x,y+ISO_H-height);ctx.closePath();ctx.fill();ctx.fillStyle=topColor;ctx.beginPath();ctx.moveTo(x,topY-ISO_H);ctx.lineTo(x+ISO_W,topY);ctx.lineTo(x,topY+ISO_H);ctx.lineTo(x-ISO_W,topY);ctx.closePath();ctx.fill();if(icon){ctx.font='14px serif';ctx.textAlign='center';ctx.fillText(icon,x,topY)}if(label){ctx.fillStyle=C.text;ctx.font='7px monospace';ctx.textAlign='center';ctx.fillText(label,x,y+ISO_H+10)}}
function drawShip(ctx:CanvasRenderingContext2D,cx:number,cy:number){ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(cx,cy+26,20,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.ship;ctx.beginPath();ctx.moveTo(cx,cy-22);ctx.lineTo(cx-16,cy+6);ctx.lineTo(cx-11,cy+18);ctx.lineTo(cx+11,cy+18);ctx.lineTo(cx+16,cy+6);ctx.closePath();ctx.fill()}

export default function WalkableColony({locationSlug,locationName,population,entities,pending,ships,userId,onClose,onEnterBuilding}:Props){
 const canvasRef=useRef<HTMLCanvasElement>(null),dragRef=useRef<{x:number;y:number;vx:number;vy:number}|null>(null)
 const[figPos,setFigPos]=useState({col:4.5,row:8.5}),[tooltip,setTooltip]=useState<string|null>(null),[viewport,setViewport]=useState({x:Math.max(0,CANVAS_W/2-VP_W/2),y:0}),[zoom,setZoom]=useState(1),[dragging,setDragging]=useState(false),[residents,setResidents]=useState<Resident[]>([]),[selectedResident,setSelectedResident]=useState<string|null>(null)
 const streets=useMemo(()=>getStreetTiles(locationSlug,population,entities,pending,userId,COLS,ROWS),[locationSlug,population,entities,pending,userId])
 const playerHabitat=entities.find(e=>e.entity_id==='habitat'&&e.profile_id===userId),landingPad=entities.find(e=>e.entity_id==='landing_pad'||e.entity_id==='docking_bay'),hasShipAtLocation=ships.some(s=>s.is_active)
 const clampViewport=useCallback((x:number,y:number,z=zoom)=>({x:Math.max(0,Math.min(CANVAS_W-VP_W/z,x)),y:Math.max(0,Math.min(CANVAS_H-VP_H/z,y))}),[zoom])
 const centerOn=useCallback((col:number,row:number,z=zoom)=>{const p=isoProject(col,row);setViewport(clampViewport(p.x-VP_W/(2*z),p.y-VP_H/(2*z),z))},[zoom,clampViewport])
 useEffect(()=>{if(playerHabitat){const p={col:playerHabitat.tile_col+.5,row:playerHabitat.tile_row+.5};setFigPos(p);centerOn(p.col,p.row)}},[playerHabitat?.id])
 useEffect(()=>{let live=true;fetch(`/api/game/population?locationSlug=${encodeURIComponent(locationSlug)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(live)setResidents(Array.isArray(d.residents)?d.residents:[])}).catch(()=>{if(live)setResidents([])});return()=>{live=false}},[locationSlug])
 const residentPositions=useMemo(()=>residents.map((r,i)=>{const work=r.assignments.find(a=>a.type==='work'&&a.tileEntityId)||r.assignments.find(a=>a.tileEntityId);const b=entities.find(e=>e.id===work?.tileEntityId);if(!b)return null;const slot=i%4;return{resident:r,col:b.tile_col+.22+(slot%2)*.42,row:b.tile_row+.18+Math.floor(slot/2)*.38,building:b}}).filter(Boolean) as {resident:Resident;col:number;row:number;building:TileEntity}[],[residents,entities])
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,CANVAS_W,CANVAS_H);ctx.fillStyle='#0a0e18';ctx.fillRect(0,0,CANVAS_W,CANVAS_H);const icons:Record<string,string>={habitat:'🏠',mine:'⛏',solar:'☀️',landing_pad:'🛬',docking_bay:'🛬',bank:'🏦',school:'🏫',academy:'🏫',research_lab:'🔬',shipyard:'⚙️',warehouse:'📦',admin:'🏛',command_center:'📡'};type Item={depth:number;draw:()=>void};const q:Item[]=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const v=((c*7+r*13)%6)*4,s=streets.find(x=>x.col===c&&x.row===r),color=s?(s.subtype==='main'?C.roadMain:s.subtype==='crossing'?C.crossing:C.road):`rgb(${61+v},${52+v},${40+v})`;q.push({depth:(c+r)*2-1000,draw:()=>drawIsoFloor(ctx,c,r,color)})}for(const e of entities){if(e.entity_type!=='building')continue;const own=e.profile_id===userId,state=e.owner_class==='STATE',corp=!!e.profile_id&&!own,color=state?C.state:own?C.habitat:corp?C.corp:C.habitat;q.push({depth:e.tile_col+e.tile_row,draw:()=>drawIsoBuilding(ctx,e.tile_col,e.tile_row,color,e.entity_id,icons[e.entity_id]??'🏗')})}if(landingPad&&hasShipAtLocation)q.push({depth:landingPad.tile_col+landingPad.tile_row+.5,draw:()=>{const p=isoProject(landingPad.tile_col,landingPad.tile_row);drawShip(ctx,p.x,p.y-BLOCK_H-10)}});for(const rp of residentPositions)q.push({depth:rp.col+rp.row+.25,draw:()=>{const p=isoProject(rp.col,rp.row);drawFigure(ctx,p.x,p.y,selectedResident===rp.resident.id?'#f0d080':C.npc,rp.resident.displayName.split(' ')[0])}});q.push({depth:figPos.col+figPos.row+.3,draw:()=>{const p=isoProject(figPos.col,figPos.row);drawFigure(ctx,p.x,p.y,C.figure,'Du')}});q.sort((a,b)=>a.depth-b.depth);q.forEach(i=>i.draw())},[figPos,streets,entities,userId,landingPad,hasShipAtLocation,residentPositions,selectedResident])
 const focusResident=(r:Resident)=>{setSelectedResident(r.id);const rp=residentPositions.find(x=>x.resident.id===r.id);if(rp)centerOn(rp.col,rp.row)}
 const isoUnproject=useCallback((px:number,py:number)=>{const dx=px-CANVAS_W/2,dy=py-60;return{col:(dx/ISO_W+dy/ISO_H)/2,row:(dy/ISO_H-dx/ISO_W)/2}},[])
 const handleClick=useCallback((e:React.MouseEvent<HTMLCanvasElement>)=>{if(dragging)return;const rect=e.currentTarget.getBoundingClientRect(),px=(e.clientX-rect.left)/zoom+viewport.x,py=(e.clientY-rect.top)/zoom+viewport.y,p=isoUnproject(px,py);const npc=residentPositions.find(x=>Math.abs(x.col-p.col)<.4&&Math.abs(x.row-p.row)<.4);if(npc){focusResident(npc.resident);setTooltip(`${npc.resident.displayName} · ${npc.resident.assignments.find(a=>a.type==='work')?.roleCode??npc.resident.activityState}`);return}const hit=entities.find(en=>Math.abs(en.tile_col-p.col)<.65&&Math.abs(en.tile_row-p.row)<.65);if(hit){if(onEnterBuilding)onEnterBuilding(hit);else setTooltip(`▶ ${hit.entity_id}`)}},[dragging,zoom,viewport,entities,onEnterBuilding,isoUnproject,residentPositions])
 const wheel=useCallback((e:React.WheelEvent)=>{e.preventDefault();const next=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,zoom*(e.deltaY>0?.9:1.1)));setZoom(next);setViewport(v=>clampViewport(v.x,v.y,next))},[zoom,clampViewport]);const pointerDown=(e:React.PointerEvent)=>{dragRef.current={x:e.clientX,y:e.clientY,vx:viewport.x,vy:viewport.y};setDragging(false);e.currentTarget.setPointerCapture(e.pointerId)},pointerMove=(e:React.PointerEvent)=>{const d=dragRef.current;if(!d)return;const dx=(e.clientX-d.x)/zoom,dy=(e.clientY-d.y)/zoom;if(Math.abs(dx)+Math.abs(dy)>4)setDragging(true);setViewport(clampViewport(d.vx-dx,d.vy-dy))},pointerUp=(e:React.PointerEvent)=>{dragRef.current=null;e.currentTarget.releasePointerCapture(e.pointerId);setTimeout(()=>setDragging(false),0)}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){onClose();return}if(e.key.toLowerCase()==='f'){centerOn(figPos.col,figPos.row);return}const step=36/zoom;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();setViewport(v=>clampViewport(v.x+(e.key==='ArrowRight'||e.key==='d'?step:e.key==='ArrowLeft'||e.key==='a'?-step:0),v.y+(e.key==='ArrowDown'||e.key==='s'?step:e.key==='ArrowUp'||e.key==='w'?-step:0)))}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[onClose,zoom,clampViewport,centerOn,figPos])
 return <div style={{position:'absolute',inset:0,zIndex:100,background:'rgba(0,0,0,.92)',display:'flex',flexDirection:'column',borderRadius:8}}><div style={{display:'flex',justifyContent:'space-between',padding:'.5rem 1rem',background:'#070b14',borderBottom:'1px solid #1d2a3d'}}><div style={{color:'#c9a961',fontFamily:'monospace',fontSize:'.75rem',fontWeight:700}}>◈ {locationName.toUpperCase()} — KOLONIEANSICHT <span style={{color:'#8aa59a',fontWeight:400}}>· {residents.length} Personen</span></div><button onClick={onClose}>ESC</button></div><div style={{flex:1,overflow:'hidden',display:'flex',alignItems:'center',justifyContent:'center',gap:12}}><div onWheel={wheel} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} style={{position:'relative',width:VP_W,height:VP_H,overflow:'hidden',border:'1px solid #1d2a3d',cursor:'grab',touchAction:'none'}}><canvas ref={canvasRef} width={CANVAS_W} height={CANVAS_H} onClick={handleClick} style={{display:'block',position:'absolute',transformOrigin:'0 0',transform:`translate(${-viewport.x*zoom}px,${-viewport.y*zoom}px) scale(${zoom})`}}/>{tooltip&&<div style={{position:'absolute',bottom:16,left:'50%',transform:'translateX(-50%)',background:'#070b14',color:'#c9a961',padding:'5px 12px'}}>{tooltip}</div>}<div style={{position:'absolute',right:10,bottom:10}}><button onClick={()=>setZoom(z=>Math.max(MIN_ZOOM,z-.15))}>−</button><button onClick={()=>centerOn(figPos.col,figPos.row)}>F</button><button onClick={()=>setZoom(z=>Math.min(MAX_ZOOM,z+.15))}>+</button></div></div><aside style={{width:220,maxHeight:VP_H,overflowY:'auto',background:'#070b14',border:'1px solid #1d2a3d',padding:8}}><div style={{color:'#c9a961',font:'bold 11px monospace',marginBottom:8}}>PERSONEN · {residents.length}</div>{residents.length===0?<div style={{color:'#64748b',font:'10px monospace'}}>Keine simulierten Personen an diesem Standort.</div>:residents.map(r=>{const work=r.assignments.find(a=>a.type==='work');return <button key={r.id} onClick={()=>focusResident(r)} style={{display:'block',width:'100%',textAlign:'left',marginBottom:5,padding:'6px 7px',background:selectedResident===r.id?'#18251f':'#0c1320',border:'1px solid #1d2a3d',color:'#d4c8b0',cursor:'pointer'}}><strong>{r.displayName}</strong><br/><span style={{fontSize:9,color:'#8aa59a'}}>{work?.roleCode??r.activityState} · {r.lastAction??'idle'}</span></button>})}</aside></div><div style={{padding:'.4rem 1rem',background:'#070b14',borderTop:'1px solid #1d2a3d',color:'#64748b',font:'10px monospace'}}>KAMERA {Math.round(zoom*100)}% · {entities.length} Gebäude · {residents.length} simulierte Personen · Klick auf Person: zentrieren</div></div>
}
