'use client'

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { getStreetTiles } from '@/lib/game/streetTiles'
import { BUILDINGS } from '@/lib/game/buildings/index'
import { BuildingSVG, BuildingSpriteStyles } from '@/lib/grid/BuildingSVG'

interface TileEntity { id:string; entity_id:string; entity_type:string; tile_row:number; tile_col:number; profile_id:string|null; owner_class:string; actor_name?:string|null; username?:string|null }
interface Ship { id:string; ship_type:string; is_active:boolean; location_id:string }
interface Assignment { type:string; roleCode:string|null; tileEntityId:string|null }
interface Need { code:string; satisfaction:number }
interface Skill { code:string; level:number; experience:number }
interface Resident { id:string; displayName:string; birthYear:number|null; activityState:string; lastAction:string|null; assignments:Assignment[]; needs:Need[]; skills:Skill[] }
interface Props { locationSlug:string; locationName:string; population:number; entities:TileEntity[]; pending:any[]; ships:Ship[]; locationId:string; userId:string; onClose:()=>void; onEnterBuilding?:(entity:TileEntity)=>void }
type Selection={kind:'building';id:string}|{kind:'person';id:string}|null

const COLS=32,ROWS=24,ISO_W=56,ISO_H=28,CANVAS_W=(COLS+ROWS)*ISO_W+240,CANVAS_H=(COLS+ROWS)*ISO_H+320,MIN_ZOOM=.5,MAX_ZOOM=2.6
const C={road:'#3d4144',roadMain:'#4b5054',crossing:'#5e6264',ship:'#6a9aca'}
function isoProject(col:number,row:number){return{x:(col-row)*ISO_W+CANVAS_W/2,y:(col+row)*ISO_H+100}}
function labelForBuilding(id:string){return BUILDINGS[id]?.name??id.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function pct(v:number){return`${Math.round(v*100)}%`}
function assignmentOf(r:Resident,type:string){return r.assignments.find(a=>a.type===type)}
function hash01(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return((h>>>0)%10000)/10000}
function lerp(a:number,b:number,t:number){return a+(b-a)*t}
function moving(r:Resident){return !!r.lastAction?.includes('travel')||r.activityState==='moving'||r.activityState==='travelling'}
function drawDiamond(ctx:CanvasRenderingContext2D,col:number,row:number,fill:string,stroke='rgba(255,220,180,.035)'){
 const{x,y}=isoProject(col,row);ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(x,y-ISO_H);ctx.lineTo(x+ISO_W,y);ctx.lineTo(x,y+ISO_H);ctx.lineTo(x-ISO_W,y);ctx.closePath();ctx.fill();ctx.strokeStyle=stroke;ctx.stroke()
}
function drawPath(ctx:CanvasRenderingContext2D,a:{x:number;y:number},b:{x:number;y:number},width:number,edge:string,fill:string){
 ctx.lineCap='round';ctx.strokeStyle=edge;ctx.lineWidth=width+5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle=fill;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()
}
function drawShip(ctx:CanvasRenderingContext2D,cx:number,cy:number){ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(cx,cy+24,27,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.ship;ctx.beginPath();ctx.moveTo(cx,cy-30);ctx.lineTo(cx-22,cy+8);ctx.lineTo(cx-14,cy+22);ctx.lineTo(cx+14,cy+22);ctx.lineTo(cx+22,cy+8);ctx.closePath();ctx.fill()}
const panelStyle:React.CSSProperties={background:'linear-gradient(180deg,#111b27,#0b121b)',border:'1px solid #45586a',boxShadow:'inset 0 0 0 1px #080d13',color:'#d8d4c8'}
const sectionStyle:React.CSSProperties={borderTop:'1px solid #344657',paddingTop:10,marginTop:10}
const actionStyle:React.CSSProperties={width:'100%',padding:'9px 10px',background:'#263d51',color:'#f4dc88',border:'1px solid #65788a',font:'bold 11px monospace',cursor:'pointer'}

function PersonSprite({resident,selected,zoom,onClick}:{resident:Resident;selected:boolean;zoom:number;onClick:()=>void}){
 const role=assignmentOf(resident,'work')?.roleCode??resident.activityState
 return <button className={`noxia-person ${moving(resident)?'walking':'idle'} ${selected?'selected':''} ${zoom>1.45?'district':''}`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onClick()}} title={`${resident.displayName} · ${role}`}><span className="shadow"/><span className="head"/><span className="body"/><span className="arm a"/><span className="arm b"/><span className="leg l"/><span className="leg r"/><span className="person-label">{resident.displayName.split(' ')[0]}{zoom>1.85?<small>{role}</small>:null}</span></button>
}

export default function WalkableColony({locationSlug,locationName,population,entities,pending,ships,userId,onClose,onEnterBuilding}:Props){
 const canvasRef=useRef<HTMLCanvasElement>(null),mapRef=useRef<HTMLDivElement>(null),dragRef=useRef<{x:number;y:number;vx:number;vy:number}|null>(null)
 const[figPos,setFigPos]=useState({col:4.5,row:8.5}),[viewport,setViewport]=useState({x:Math.max(0,CANVAS_W/2-500),y:0}),[zoom,setZoom]=useState(.78),[residents,setResidents]=useState<Resident[]>([]),[selection,setSelection]=useState<Selection>(null),[showPeople,setShowPeople]=useState(false),[motionTick,setMotionTick]=useState(0)
 const buildings=useMemo(()=>entities.filter(e=>e.entity_type==='building'),[entities])
 const streets=useMemo(()=>getStreetTiles(locationSlug,population,entities,pending,userId,COLS,ROWS),[locationSlug,population,entities,pending,userId])
 const streetMap=useMemo(()=>new Map(streets.map(s=>[`${s.col}:${s.row}`,s])),[streets])
 const playerHabitat=entities.find(e=>e.entity_id==='habitat'&&e.profile_id===userId),landingPad=entities.find(e=>e.entity_id==='landing_pad'||e.entity_id==='docking_bay'),hasShipAtLocation=ships.some(s=>s.is_active)
 const selectedBuilding=selection?.kind==='building'?entities.find(e=>e.id===selection.id)??null:null,selectedPerson=selection?.kind==='person'?residents.find(r=>r.id===selection.id)??null:null
 const colonyCenter=useMemo(()=>{if(!buildings.length)return{col:COLS/2,row:ROWS/2};return{col:buildings.reduce((s,b)=>s+b.tile_col+.5,0)/buildings.length,row:buildings.reduce((s,b)=>s+b.tile_row+.5,0)/buildings.length}},[buildings])
 const clampViewport=useCallback((x:number,y:number,z=zoom)=>{const rect=mapRef.current?.getBoundingClientRect();const w=(rect?.width??900)/z,h=(rect?.height??560)/z;return{x:Math.max(0,Math.min(Math.max(0,CANVAS_W-w),x)),y:Math.max(0,Math.min(Math.max(0,CANVAS_H-h),y))}},[zoom])
 const centerOn=useCallback((col:number,row:number,z=zoom)=>{const p=isoProject(col,row),rect=mapRef.current?.getBoundingClientRect();setViewport(clampViewport(p.x-(rect?.width??900)/(2*z),p.y-(rect?.height??560)/(2*z),z))},[zoom,clampViewport])
 useEffect(()=>{if(playerHabitat){const p={col:playerHabitat.tile_col+.5,row:playerHabitat.tile_row+.5};setFigPos(p);centerOn(p.col,p.row)}else centerOn(colonyCenter.col,colonyCenter.row)},[playerHabitat?.id,colonyCenter.col,colonyCenter.row])
 useEffect(()=>{let live=true;fetch(`/api/game/population?locationSlug=${encodeURIComponent(locationSlug)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(live)setResidents(Array.isArray(d.residents)?d.residents:[])}).catch(()=>{if(live)setResidents([])});return()=>{live=false}},[locationSlug])
 useEffect(()=>{const id=window.setInterval(()=>setMotionTick(t=>t+1),450);return()=>window.clearInterval(id)},[])
 const nearestStreet=useCallback((b:TileEntity)=>{let best:{col:number;row:number}|null=null,bestD=Infinity;for(const s of streets){const d=Math.abs(s.col-b.tile_col)+Math.abs(s.row-b.tile_row);if(d<bestD){bestD=d;best={col:s.col,row:s.row}}}return best},[streets])
 const residentPositions=useMemo(()=>residents.map((r)=>{const work=assignmentOf(r,'work'),home=assignmentOf(r,'home');const wb=entities.find(e=>e.id===work?.tileEntityId),hb=entities.find(e=>e.id===home?.tileEntityId);const fallback=wb??hb;if(!fallback)return null;let col=fallback.tile_col+.5,row=fallback.tile_row+.5;if(moving(r)&&wb&&hb&&wb.id!==hb.id){const phase=(motionTick*.06+hash01(r.id))%2,t=phase<=1?phase:2-phase;col=lerp(hb.tile_col+.5,wb.tile_col+.5,t);row=lerp(hb.tile_row+.5,wb.tile_row+.5,t)}else{const angle=hash01(r.id+'a')*Math.PI*2,rad=.5+hash01(r.id+'b')*.35;col+=Math.cos(angle)*rad;row+=Math.sin(angle)*rad}return{resident:r,col,row,building:fallback}}).filter(Boolean) as {resident:Resident;col:number;row:number;building:TileEntity}[],[residents,entities,motionTick])

 useEffect(()=>{
  const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return
  ctx.clearRect(0,0,CANVAS_W,CANVAS_H);ctx.fillStyle=locationSlug==='mars'?'#120905':'#080d14';ctx.fillRect(0,0,CANVAS_W,CANVAS_H)
  for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){
   const s=streetMap.get(`${c}:${r}`),noise=((c*19+r*31+c*r*3)%11),base=locationSlug==='mars'?[79+noise*2,41+noise,25+Math.floor(noise*.6)]:[40+noise,42+noise,43+noise]
   const color=s?(s.subtype==='main'?C.roadMain:s.subtype==='crossing'?C.crossing:C.road):`rgb(${base[0]},${base[1]},${base[2]})`
   drawDiamond(ctx,c,r,color,s?'rgba(205,220,220,.16)':'rgba(255,220,180,.025)')
   if(s){const p=isoProject(c,r);ctx.strokeStyle=s.subtype==='main'?'rgba(225,190,105,.38)':'rgba(205,215,215,.20)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x-ISO_W*.55,p.y);ctx.lineTo(p.x+ISO_W*.55,p.y);ctx.stroke()}
   if(locationSlug==='mars'&&!s){const h=hash01(`${c}:${r}`);const p=isoProject(c+.35+h*.3,r+.25+(1-h)*.3);if(h>.83){ctx.fillStyle='rgba(25,8,4,.28)';ctx.beginPath();ctx.ellipse(p.x,p.y,12+h*12,4+h*5,-.18,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(151,82,48,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x-2,p.y-2,7+h*7,2.5+h*3,-.18,Math.PI,Math.PI*2);ctx.stroke()}else if(h<.12){ctx.fillStyle='rgba(109,54,30,.8)';ctx.beginPath();ctx.moveTo(p.x-7,p.y);ctx.lineTo(p.x-1,p.y-12-h*20);ctx.lineTo(p.x+9,p.y-1);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(185,105,64,.25)';ctx.beginPath();ctx.moveTo(p.x-1,p.y-11);ctx.lineTo(p.x+2,p.y-4);ctx.lineTo(p.x+8,p.y-1);ctx.closePath();ctx.fill()}}
  }
  for(const b of buildings){const p=isoProject(b.tile_col+.5,b.tile_row+.5);ctx.fillStyle='rgba(11,16,20,.55)';ctx.beginPath();ctx.moveTo(p.x,p.y-30);ctx.lineTo(p.x+58,p.y);ctx.lineTo(p.x,p.y+30);ctx.lineTo(p.x-58,p.y);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(165,185,185,.32)';ctx.stroke();const s=nearestStreet(b);if(s){const q=isoProject(s.col+.5,s.row+.5);drawPath(ctx,p,q,8,'rgba(24,20,18,.92)','rgba(94,88,78,.96)')}}
  const sorted=[...buildings].sort((a,b)=>(a.tile_col+a.tile_row)-(b.tile_col+b.tile_row));for(let i=1;i<sorted.length;i++){const a=isoProject(sorted[i-1].tile_col+.5,sorted[i-1].tile_row+.5),b=isoProject(sorted[i].tile_col+.5,sorted[i].tile_row+.5);if(Math.hypot(a.x-b.x,a.y-b.y)<260)drawPath(ctx,a,b,4,'rgba(34,25,20,.7)','rgba(142,117,85,.52)')}
  if(landingPad&&hasShipAtLocation){const p=isoProject(landingPad.tile_col+.5,landingPad.tile_row+.5);drawShip(ctx,p.x,p.y-52)}
 },[streetMap,buildings,nearestStreet,landingPad,hasShipAtLocation,locationSlug])

 const selectBuilding=(b:TileEntity)=>{setSelection({kind:'building',id:b.id});setShowPeople(false)}
 const focusPerson=(r:Resident)=>{setSelection({kind:'person',id:r.id});setShowPeople(false);const rp=residentPositions.find(x=>x.resident.id===r.id);if(rp)centerOn(rp.col,rp.row,Math.max(zoom,1.5))}
 const enterSelected=()=>{if(selectedBuilding&&onEnterBuilding)onEnterBuilding(selectedBuilding)}
 const wheel=useCallback((e:React.WheelEvent)=>{e.preventDefault();const rect=mapRef.current?.getBoundingClientRect();if(!rect)return;const lx=e.clientX-rect.left,ly=e.clientY-rect.top,next=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,zoom*(e.deltaY>0?.88:1.14))),worldX=viewport.x+lx/zoom,worldY=viewport.y+ly/zoom;setZoom(next);setViewport(clampViewport(worldX-lx/next,worldY-ly/next,next))},[zoom,viewport,clampViewport])
 const pointerDown=(e:React.PointerEvent)=>{dragRef.current={x:e.clientX,y:e.clientY,vx:viewport.x,vy:viewport.y};e.currentTarget.setPointerCapture(e.pointerId)},pointerMove=(e:React.PointerEvent)=>{const d=dragRef.current;if(!d)return;setViewport(clampViewport(d.vx-(e.clientX-d.x)/zoom,d.vy-(e.clientY-d.y)/zoom))},pointerUp=(e:React.PointerEvent)=>{dragRef.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(selection){setSelection(null);return}onClose();return}if(e.key==='Enter'&&selectedBuilding){enterSelected();return}if(e.key.toLowerCase()==='f'){centerOn(figPos.col,figPos.row);return}const step=55/zoom;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();setViewport(v=>clampViewport(v.x+(e.key==='ArrowRight'||e.key==='d'?step:e.key==='ArrowLeft'||e.key==='a'?-step:0),v.y+(e.key==='ArrowDown'||e.key==='s'?step:e.key==='ArrowUp'||e.key==='w'?-step:0)))}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[onClose,selection,selectedBuilding,zoom,clampViewport,centerOn,figPos])
 const workers=selectedBuilding?residents.filter(r=>r.assignments.some(a=>a.type==='work'&&a.tileEntityId===selectedBuilding.id)):[],homeResidents=selectedBuilding?residents.filter(r=>r.assignments.some(a=>a.type==='home'&&a.tileEntityId===selectedBuilding.id)):[]
 const lowNeed=selectedPerson?[...selectedPerson.needs].sort((a,b)=>a.satisfaction-b.satisfaction)[0]:null,work=selectedPerson?assignmentOf(selectedPerson,'work'):null,home=selectedPerson?assignmentOf(selectedPerson,'home'):null
 const workBuilding=work?.tileEntityId?entities.find(e=>e.id===work.tileEntityId):null,homeBuilding=home?.tileEntityId?entities.find(e=>e.id===home.tileEntityId):null
 const worldTransform=`translate(${-viewport.x*zoom}px,${-viewport.y*zoom}px) scale(${zoom})`,district=zoom>=1.45
 const depthItems=useMemo(()=>[...buildings.map(b=>({kind:'building' as const,depth:b.tile_col+b.tile_row,building:b})),...residentPositions.map(p=>({kind:'person' as const,depth:p.col+p.row,person:p}))].sort((a,b)=>a.depth-b.depth),[buildings,residentPositions])

 return <div style={{position:'absolute',inset:0,zIndex:100,background:'#081019',display:'grid',gridTemplateRows:'42px minmax(0,1fr) 48px',border:'1px solid #4b6174',fontFamily:'monospace'}}><BuildingSpriteStyles/><style>{`.noxia-building{transition:filter .2s ease,transform .2s ease}.noxia-building:hover{filter:drop-shadow(0 0 10px #e1bd5788) drop-shadow(0 14px 10px #0009)}.noxia-building .beacon{position:absolute;left:50%;top:7px;width:4px;height:4px;border-radius:50%;background:#f2bf4d;box-shadow:0 0 7px #f2bf4d;animation:nox-beacon 1.8s ease-in-out infinite}.noxia-person{position:absolute;width:22px;height:34px;border:0;background:transparent;padding:0;cursor:pointer;filter:drop-shadow(0 3px 2px #0008);transform-origin:50% 100%}.noxia-person .shadow{position:absolute;left:3px;top:27px;width:17px;height:5px;border-radius:50%;background:#0006}.noxia-person .head{position:absolute;left:7px;top:1px;width:8px;height:8px;border-radius:50%;background:#d8ad79;border:1px solid #263442}.noxia-person .body{position:absolute;left:5px;top:9px;width:12px;height:13px;border-radius:3px;background:#c9942e;border:1px solid #273848}.noxia-person .arm{position:absolute;top:11px;width:3px;height:10px;background:#b9852d}.noxia-person .arm.a{left:2px}.noxia-person .arm.b{left:17px}.noxia-person .leg{position:absolute;top:21px;width:4px;height:9px;background:#263848}.noxia-person .leg.l{left:5px}.noxia-person .leg.r{left:12px}.noxia-person.walking .leg.l,.noxia-person.walking .arm.b{animation:nox-leg .55s infinite alternate}.noxia-person.walking .leg.r,.noxia-person.walking .arm.a{animation:nox-leg .55s infinite alternate-reverse}.noxia-person.idle{animation:nox-idle 2.2s ease-in-out infinite}.noxia-person.selected{filter:drop-shadow(0 0 5px #ffe27b)}.noxia-person.selected:after{content:'';position:absolute;left:0;top:-4px;width:21px;height:31px;border:1px solid #ffe27b;border-radius:50%}.person-label{display:none;position:absolute;top:-14px;left:50%;transform:translateX(-50%);white-space:nowrap;background:#0b131deb;color:#f1e7d4;border:1px solid #52677a;padding:2px 4px;font:7px monospace}.person-label small{display:block;color:#9bc7ad;font-size:6px}.noxia-person:hover .person-label,.noxia-person.selected .person-label,.noxia-person.district .person-label{display:block}@keyframes nox-leg{from{transform:rotate(-16deg)}to{transform:rotate(16deg)}}@keyframes nox-idle{0%,100%{transform:translateY(0)}50%{transform:translateY(-1px)}}@keyframes nox-beacon{0%,100%{opacity:.25}50%{opacity:1}}`}</style>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'0 12px',background:'linear-gradient(180deg,#1b2b3b,#142230)',borderBottom:'1px solid #526779',color:'#f1d57a'}}><div style={{fontWeight:700,fontSize:12}}>NOXIA · {locationName.toUpperCase()} <span style={{color:'#9eabb8',fontWeight:400}}>POP {population.toLocaleString()} · SIM {residents.length} · {district?'DISTRIKT':'STRATEGIE'}</span></div><div style={{display:'flex',gap:6}}><button onClick={()=>setShowPeople(v=>!v)} style={{...actionStyle,width:'auto',padding:'5px 10px'}}>PERSONEN [{residents.length}]</button><button onClick={onClose} style={{...actionStyle,width:'auto',padding:'5px 10px'}}>KARTE SCHLIESSEN</button></div></header>
  <main style={{minHeight:0,display:'grid',gridTemplateColumns:'minmax(0,1fr) 285px'}}><div ref={mapRef} style={{position:'relative',overflow:'hidden',background:'#050912',cursor:dragRef.current?'grabbing':'grab'}} onWheel={wheel} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp}>
   <canvas ref={canvasRef} width={CANVAS_W} height={CANVAS_H} style={{position:'absolute',left:0,top:0,transformOrigin:'0 0',transform:worldTransform,pointerEvents:'none'}}/>
   <div style={{position:'absolute',left:0,top:0,width:CANVAS_W,height:CANVAS_H,transformOrigin:'0 0',transform:worldTransform,pointerEvents:'none'}}>{depthItems.map(item=>{if(item.kind==='building'){const b=item.building,p=isoProject(b.tile_col+.5,b.tile_row+.5),selected=selection?.kind==='building'&&selection.id===b.id;return <button className="noxia-building" key={`b-${b.id}`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();selectBuilding(b)}} onDoubleClick={e=>{e.stopPropagation();onEnterBuilding?.(b)}} title={`${labelForBuilding(b.entity_id)} — Doppelklick: betreten`} style={{position:'absolute',left:p.x-52,top:p.y-95,width:104,height:108,padding:0,background:selected?'radial-gradient(ellipse,rgba(241,213,122,.28),transparent 70%)':'transparent',border:selected?'1px solid #f1d57a':'1px solid transparent',borderRadius:16,cursor:'pointer',pointerEvents:'auto',filter:'drop-shadow(0 14px 10px rgba(0,0,0,.58))',zIndex:Math.round(item.depth*10)}}><span className="beacon"/><BuildingSVG entityId={b.entity_id} planet={locationSlug} owned={b.profile_id===userId} size={district?94:86}/>{(district||selected)&&<span style={{position:'absolute',top:88,left:'50%',transform:'translateX(-50%)',whiteSpace:'nowrap',font:'8px monospace',padding:'2px 4px',background:'#0b131ded',border:'1px solid #43576a',color:'#f0e7d8'}}>{labelForBuilding(b.entity_id)}</span>}</button>}const rp=item.person,p=isoProject(rp.col,rp.row);return <div key={`p-${rp.resident.id}`} style={{position:'absolute',left:p.x-11,top:p.y-31,width:22,height:34,pointerEvents:'auto',zIndex:Math.round(item.depth*10)+5}}><PersonSprite resident={rp.resident} selected={selection?.kind==='person'&&selection.id===rp.resident.id} zoom={zoom} onClick={()=>focusPerson(rp.resident)}/></div>})}</div>
   <div style={{position:'absolute',left:10,top:10,padding:'6px 8px',background:'rgba(7,12,18,.84)',border:'1px solid #43586a',color:'#aebbc7',fontSize:9}}>MAUSRAD: ZOOM ZUM CURSOR · ZIEHEN/WASD: KAMERA · DOPPELKLICK: BETRETEN · F: FIGUR</div><div style={{position:'absolute',right:10,bottom:10,display:'flex',gap:4}}><button onClick={()=>setZoom(z=>Math.max(MIN_ZOOM,z-.15))}>−</button><button onClick={()=>centerOn(figPos.col,figPos.row)}>F</button><button onClick={()=>setZoom(z=>Math.min(MAX_ZOOM,z+.15))}>+</button></div>
  </div><aside style={{...panelStyle,minHeight:0,overflowY:'auto',padding:10}}>{showPeople?<><div style={{fontSize:11,fontWeight:700,color:'#f1d57a',marginBottom:8}}>BEVÖLKERUNG · {residents.length}</div>{residents.map(r=>{const w=assignmentOf(r,'work');return <button key={r.id} onClick={()=>focusPerson(r)} style={{display:'block',width:'100%',textAlign:'left',padding:7,marginBottom:5,background:'#172231',border:'1px solid #536273',color:'#ddd6c7',cursor:'pointer'}}><strong>{r.displayName}</strong><br/><span style={{fontSize:9,color:'#8fbca6'}}>{w?.roleCode??r.activityState} · {r.lastAction??'idle'}</span></button>})}</>:selectedBuilding?<><div style={{fontSize:10,color:'#8fa1b4'}}>GEBÄUDE</div><div style={{fontSize:15,fontWeight:700,color:'#f1d57a',margin:'2px 0 8px'}}>{labelForBuilding(selectedBuilding.entity_id)}</div><div style={{fontSize:10,lineHeight:1.55}}>Koordinate {selectedBuilding.tile_col},{selectedBuilding.tile_row}<br/>Eigentum: {selectedBuilding.profile_id===userId?'du':selectedBuilding.owner_class==='STATE'?'staatlich':selectedBuilding.actor_name??selectedBuilding.username??'fremd'}</div><div style={sectionStyle}>PERSONAL · {workers.length} Arbeitende · {homeResidents.length} Wohnende{workers.slice(0,5).map(r=><button key={r.id} onClick={()=>focusPerson(r)} style={{display:'block',background:'none',border:0,color:'#8fbca6',padding:'3px 0',cursor:'pointer',font:'10px monospace'}}>› {r.displayName} · {assignmentOf(r,'work')?.roleCode}</button>)}</div><div style={sectionStyle}><button onClick={enterSelected} style={actionStyle}>BETRETEN</button></div></>:selectedPerson?<><div style={{fontSize:10,color:'#8fa1b4'}}>PERSON</div><div style={{fontSize:15,fontWeight:700,color:'#f1d57a'}}>{selectedPerson.displayName}</div><div style={{fontSize:10,color:'#8fbca6'}}>{work?.roleCode??selectedPerson.activityState} · {selectedPerson.lastAction??'idle'}</div><div style={sectionStyle}>Arbeit: {workBuilding?labelForBuilding(workBuilding.entity_id):'—'}<br/>Wohnen: {homeBuilding?labelForBuilding(homeBuilding.entity_id):'—'}</div><div style={sectionStyle}>BEDÜRFNISSE{selectedPerson.needs.map(n=><div key={n.code} style={{fontSize:9}}>{n.code}: {pct(n.satisfaction)}</div>)}</div><div style={sectionStyle}>KOMPETENZEN{selectedPerson.skills.map(s=><div key={s.code} style={{fontSize:9}}>{s.code}: {pct(s.level)} · XP {s.experience}</div>)}</div><div style={sectionStyle}>BEOBACHTUNG<br/><span style={{fontSize:9}}>{lowNeed&&lowNeed.satisfaction<.6?`${lowNeed.code} ist auffällig niedrig (${pct(lowNeed.satisfaction)}).`:'Keine kritische persönliche Abweichung erkannt.'}</span></div></>:<><div style={{fontSize:11,fontWeight:700,color:'#f1d57a'}}>KOLONIEKONTROLLE</div><div style={{fontSize:10,lineHeight:1.6,marginTop:8}}>Gebäude stehen jetzt auf eigenen Pads, werden über Servicewege angebunden und haben mehr Abstand. Ab 145 % werden Personen und Gebäudenamen direkt lesbar.</div></>}</aside></main>
  <footer style={{display:'grid',gridTemplateColumns:'1fr auto',alignItems:'center',padding:'0 10px',background:'#172230',borderTop:'1px solid #526779',color:'#9eabb8',fontSize:9}}><div>{selection?.kind==='building'?`AUSWAHL: ${selectedBuilding?labelForBuilding(selectedBuilding.entity_id):'—'}`:selection?.kind==='person'?`AUSWAHL: ${selectedPerson?.displayName??'—'}`:'BEREIT'} · {buildings.length} GEBÄUDE · {residents.length} SIMULIERTE PERSONEN</div><div>ZOOM {Math.round(zoom*100)}% · {district?'DISTRIKT':'STRATEGIE'}</div></footer>
 </div>
}
